/**
 */
package org.devboost.stanford.language.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.devboost.stanford.language.Collapse;
import org.devboost.stanford.language.Dependency;
import org.devboost.stanford.language.Word;
import org.devboost.stanford.language.util.LanguageAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class LanguageItemProviderAdapterFactory extends LanguageAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	
	/**
	 * @generated NOT
	 */
	@Override
	public Adapter createAdapter(Notifier target) {
		if(target instanceof Word){
			return createWordAdapter();
		}
		if(target instanceof Collapse){
			return createCollapseAdapter();
		}
		if(target instanceof Dependency){
			return createDependencyAdapter();
		}
		return super.createAdapter(target);
	}

	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public LanguageItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Document} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentItemProvider documentItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Document}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentAdapter() {
		if (documentItemProvider == null) {
			documentItemProvider = new DocumentItemProvider(this);
		}

		return documentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Sentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SentenceItemProvider sentenceItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Sentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSentenceAdapter() {
		if (sentenceItemProvider == null) {
			sentenceItemProvider = new SentenceItemProvider(this);
		}

		return sentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Word} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WordItemProvider wordItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Word}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWordAdapter() {
		if (wordItemProvider == null) {
			wordItemProvider = new WordItemProvider(this);
		}

		return wordItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.CC} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CCItemProvider ccItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.CC}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCCAdapter() {
		if (ccItemProvider == null) {
			ccItemProvider = new CCItemProvider(this);
		}

		return ccItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.CD} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CDItemProvider cdItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.CD}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCDAdapter() {
		if (cdItemProvider == null) {
			cdItemProvider = new CDItemProvider(this);
		}

		return cdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.DT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DTItemProvider dtItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.DT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDTAdapter() {
		if (dtItemProvider == null) {
			dtItemProvider = new DTItemProvider(this);
		}

		return dtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.EX} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EXItemProvider exItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.EX}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEXAdapter() {
		if (exItemProvider == null) {
			exItemProvider = new EXItemProvider(this);
		}

		return exItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.FW} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FWItemProvider fwItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.FW}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFWAdapter() {
		if (fwItemProvider == null) {
			fwItemProvider = new FWItemProvider(this);
		}

		return fwItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.IN} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected INItemProvider inItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.IN}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createINAdapter() {
		if (inItemProvider == null) {
			inItemProvider = new INItemProvider(this);
		}

		return inItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.JJ} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JJItemProvider jjItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.JJ}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJJAdapter() {
		if (jjItemProvider == null) {
			jjItemProvider = new JJItemProvider(this);
		}

		return jjItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.JJR} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JJRItemProvider jjrItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.JJR}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJJRAdapter() {
		if (jjrItemProvider == null) {
			jjrItemProvider = new JJRItemProvider(this);
		}

		return jjrItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.JJS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JJSItemProvider jjsItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.JJS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJJSAdapter() {
		if (jjsItemProvider == null) {
			jjsItemProvider = new JJSItemProvider(this);
		}

		return jjsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.LS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LSItemProvider lsItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.LS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLSAdapter() {
		if (lsItemProvider == null) {
			lsItemProvider = new LSItemProvider(this);
		}

		return lsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.MD} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MDItemProvider mdItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.MD}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMDAdapter() {
		if (mdItemProvider == null) {
			mdItemProvider = new MDItemProvider(this);
		}

		return mdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.NN} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NNItemProvider nnItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.NN}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNNAdapter() {
		if (nnItemProvider == null) {
			nnItemProvider = new NNItemProvider(this);
		}

		return nnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.NNS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NNSItemProvider nnsItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.NNS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNNSAdapter() {
		if (nnsItemProvider == null) {
			nnsItemProvider = new NNSItemProvider(this);
		}

		return nnsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.NNP} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NNPItemProvider nnpItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.NNP}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNNPAdapter() {
		if (nnpItemProvider == null) {
			nnpItemProvider = new NNPItemProvider(this);
		}

		return nnpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.NNPS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NNPSItemProvider nnpsItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.NNPS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNNPSAdapter() {
		if (nnpsItemProvider == null) {
			nnpsItemProvider = new NNPSItemProvider(this);
		}

		return nnpsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.PDT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PDTItemProvider pdtItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.PDT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPDTAdapter() {
		if (pdtItemProvider == null) {
			pdtItemProvider = new PDTItemProvider(this);
		}

		return pdtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.POS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected POSItemProvider posItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.POS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPOSAdapter() {
		if (posItemProvider == null) {
			posItemProvider = new POSItemProvider(this);
		}

		return posItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.PRP} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PRPItemProvider prpItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.PRP}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPRPAdapter() {
		if (prpItemProvider == null) {
			prpItemProvider = new PRPItemProvider(this);
		}

		return prpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.PRPS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PRPSItemProvider prpsItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.PRPS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPRPSAdapter() {
		if (prpsItemProvider == null) {
			prpsItemProvider = new PRPSItemProvider(this);
		}

		return prpsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.RB} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RBItemProvider rbItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.RB}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRBAdapter() {
		if (rbItemProvider == null) {
			rbItemProvider = new RBItemProvider(this);
		}

		return rbItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.RBR} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RBRItemProvider rbrItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.RBR}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRBRAdapter() {
		if (rbrItemProvider == null) {
			rbrItemProvider = new RBRItemProvider(this);
		}

		return rbrItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.RBS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RBSItemProvider rbsItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.RBS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRBSAdapter() {
		if (rbsItemProvider == null) {
			rbsItemProvider = new RBSItemProvider(this);
		}

		return rbsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.RP} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RPItemProvider rpItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.RP}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRPAdapter() {
		if (rpItemProvider == null) {
			rpItemProvider = new RPItemProvider(this);
		}

		return rpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.SYM} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SYMItemProvider symItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.SYM}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSYMAdapter() {
		if (symItemProvider == null) {
			symItemProvider = new SYMItemProvider(this);
		}

		return symItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.TO} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TOItemProvider toItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.TO}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTOAdapter() {
		if (toItemProvider == null) {
			toItemProvider = new TOItemProvider(this);
		}

		return toItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.UH} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UHItemProvider uhItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.UH}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUHAdapter() {
		if (uhItemProvider == null) {
			uhItemProvider = new UHItemProvider(this);
		}

		return uhItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.VB} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VBItemProvider vbItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.VB}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVBAdapter() {
		if (vbItemProvider == null) {
			vbItemProvider = new VBItemProvider(this);
		}

		return vbItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.VBD} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VBDItemProvider vbdItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.VBD}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVBDAdapter() {
		if (vbdItemProvider == null) {
			vbdItemProvider = new VBDItemProvider(this);
		}

		return vbdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.VBG} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VBGItemProvider vbgItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.VBG}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVBGAdapter() {
		if (vbgItemProvider == null) {
			vbgItemProvider = new VBGItemProvider(this);
		}

		return vbgItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.VBN} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VBNItemProvider vbnItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.VBN}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVBNAdapter() {
		if (vbnItemProvider == null) {
			vbnItemProvider = new VBNItemProvider(this);
		}

		return vbnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.VBP} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VBPItemProvider vbpItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.VBP}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVBPAdapter() {
		if (vbpItemProvider == null) {
			vbpItemProvider = new VBPItemProvider(this);
		}

		return vbpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.VBZ} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VBZItemProvider vbzItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.VBZ}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVBZAdapter() {
		if (vbzItemProvider == null) {
			vbzItemProvider = new VBZItemProvider(this);
		}

		return vbzItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.WDT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WDTItemProvider wdtItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.WDT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWDTAdapter() {
		if (wdtItemProvider == null) {
			wdtItemProvider = new WDTItemProvider(this);
		}

		return wdtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.WP} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WPItemProvider wpItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.WP}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWPAdapter() {
		if (wpItemProvider == null) {
			wpItemProvider = new WPItemProvider(this);
		}

		return wpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.WPS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WPSItemProvider wpsItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.WPS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWPSAdapter() {
		if (wpsItemProvider == null) {
			wpsItemProvider = new WPSItemProvider(this);
		}

		return wpsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.WRB} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WRBItemProvider wrbItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.WRB}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWRBAdapter() {
		if (wrbItemProvider == null) {
			wrbItemProvider = new WRBItemProvider(this);
		}

		return wrbItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.PlainText} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlainTextItemProvider plainTextItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.PlainText}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlainTextAdapter() {
		if (plainTextItemProvider == null) {
			plainTextItemProvider = new PlainTextItemProvider(this);
		}

		return plainTextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dependency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependencyItemProvider dependencyItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dependency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDependencyAdapter() {
		if (dependencyItemProvider == null) {
			dependencyItemProvider = new DependencyItemProvider(this);
		}

		return dependencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dabbrev} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DabbrevItemProvider dabbrevItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dabbrev}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDabbrevAdapter() {
		if (dabbrevItemProvider == null) {
			dabbrevItemProvider = new DabbrevItemProvider(this);
		}

		return dabbrevItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dacomp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DacompItemProvider dacompItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dacomp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDacompAdapter() {
		if (dacompItemProvider == null) {
			dacompItemProvider = new DacompItemProvider(this);
		}

		return dacompItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dadvcl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DadvclItemProvider dadvclItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dadvcl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDadvclAdapter() {
		if (dadvclItemProvider == null) {
			dadvclItemProvider = new DadvclItemProvider(this);
		}

		return dadvclItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dadvmod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DadvmodItemProvider dadvmodItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dadvmod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDadvmodAdapter() {
		if (dadvmodItemProvider == null) {
			dadvmodItemProvider = new DadvmodItemProvider(this);
		}

		return dadvmodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dagent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DagentItemProvider dagentItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dagent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDagentAdapter() {
		if (dagentItemProvider == null) {
			dagentItemProvider = new DagentItemProvider(this);
		}

		return dagentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Damod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DamodItemProvider damodItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Damod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDamodAdapter() {
		if (damodItemProvider == null) {
			damodItemProvider = new DamodItemProvider(this);
		}

		return damodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dappos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DapposItemProvider dapposItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dappos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDapposAdapter() {
		if (dapposItemProvider == null) {
			dapposItemProvider = new DapposItemProvider(this);
		}

		return dapposItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dattr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DattrItemProvider dattrItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dattr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDattrAdapter() {
		if (dattrItemProvider == null) {
			dattrItemProvider = new DattrItemProvider(this);
		}

		return dattrItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Daux} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DauxItemProvider dauxItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Daux}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDauxAdapter() {
		if (dauxItemProvider == null) {
			dauxItemProvider = new DauxItemProvider(this);
		}

		return dauxItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dauxpass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DauxpassItemProvider dauxpassItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dauxpass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDauxpassAdapter() {
		if (dauxpassItemProvider == null) {
			dauxpassItemProvider = new DauxpassItemProvider(this);
		}

		return dauxpassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dcc} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DccItemProvider dccItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dcc}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDccAdapter() {
		if (dccItemProvider == null) {
			dccItemProvider = new DccItemProvider(this);
		}

		return dccItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dccomp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DccompItemProvider dccompItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dccomp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDccompAdapter() {
		if (dccompItemProvider == null) {
			dccompItemProvider = new DccompItemProvider(this);
		}

		return dccompItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dcomplm} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DcomplmItemProvider dcomplmItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dcomplm}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDcomplmAdapter() {
		if (dcomplmItemProvider == null) {
			dcomplmItemProvider = new DcomplmItemProvider(this);
		}

		return dcomplmItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dconj} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DconjItemProvider dconjItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dconj}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDconjAdapter() {
		if (dconjItemProvider == null) {
			dconjItemProvider = new DconjItemProvider(this);
		}

		return dconjItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dcop} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DcopItemProvider dcopItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dcop}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDcopAdapter() {
		if (dcopItemProvider == null) {
			dcopItemProvider = new DcopItemProvider(this);
		}

		return dcopItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dcsubj} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DcsubjItemProvider dcsubjItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dcsubj}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDcsubjAdapter() {
		if (dcsubjItemProvider == null) {
			dcsubjItemProvider = new DcsubjItemProvider(this);
		}

		return dcsubjItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dcsubjpass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DcsubjpassItemProvider dcsubjpassItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dcsubjpass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDcsubjpassAdapter() {
		if (dcsubjpassItemProvider == null) {
			dcsubjpassItemProvider = new DcsubjpassItemProvider(this);
		}

		return dcsubjpassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Ddep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdepItemProvider ddepItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Ddep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdepAdapter() {
		if (ddepItemProvider == null) {
			ddepItemProvider = new DdepItemProvider(this);
		}

		return ddepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Ddet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdetItemProvider ddetItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Ddet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdetAdapter() {
		if (ddetItemProvider == null) {
			ddetItemProvider = new DdetItemProvider(this);
		}

		return ddetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Ddobj} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdobjItemProvider ddobjItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Ddobj}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdobjAdapter() {
		if (ddobjItemProvider == null) {
			ddobjItemProvider = new DdobjItemProvider(this);
		}

		return ddobjItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dexpl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DexplItemProvider dexplItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dexpl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDexplAdapter() {
		if (dexplItemProvider == null) {
			dexplItemProvider = new DexplItemProvider(this);
		}

		return dexplItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dinfmod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DinfmodItemProvider dinfmodItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dinfmod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDinfmodAdapter() {
		if (dinfmodItemProvider == null) {
			dinfmodItemProvider = new DinfmodItemProvider(this);
		}

		return dinfmodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Diobj} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiobjItemProvider diobjItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Diobj}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiobjAdapter() {
		if (diobjItemProvider == null) {
			diobjItemProvider = new DiobjItemProvider(this);
		}

		return diobjItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dmark} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DmarkItemProvider dmarkItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dmark}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDmarkAdapter() {
		if (dmarkItemProvider == null) {
			dmarkItemProvider = new DmarkItemProvider(this);
		}

		return dmarkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dmwe} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DmweItemProvider dmweItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dmwe}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDmweAdapter() {
		if (dmweItemProvider == null) {
			dmweItemProvider = new DmweItemProvider(this);
		}

		return dmweItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dneg} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DnegItemProvider dnegItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dneg}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDnegAdapter() {
		if (dnegItemProvider == null) {
			dnegItemProvider = new DnegItemProvider(this);
		}

		return dnegItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dnn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DnnItemProvider dnnItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dnn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDnnAdapter() {
		if (dnnItemProvider == null) {
			dnnItemProvider = new DnnItemProvider(this);
		}

		return dnnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dnpadvmod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DnpadvmodItemProvider dnpadvmodItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dnpadvmod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDnpadvmodAdapter() {
		if (dnpadvmodItemProvider == null) {
			dnpadvmodItemProvider = new DnpadvmodItemProvider(this);
		}

		return dnpadvmodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dnsubj} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DnsubjItemProvider dnsubjItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dnsubj}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDnsubjAdapter() {
		if (dnsubjItemProvider == null) {
			dnsubjItemProvider = new DnsubjItemProvider(this);
		}

		return dnsubjItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dnsubjpass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DnsubjpassItemProvider dnsubjpassItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dnsubjpass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDnsubjpassAdapter() {
		if (dnsubjpassItemProvider == null) {
			dnsubjpassItemProvider = new DnsubjpassItemProvider(this);
		}

		return dnsubjpassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dnum} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DnumItemProvider dnumItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dnum}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDnumAdapter() {
		if (dnumItemProvider == null) {
			dnumItemProvider = new DnumItemProvider(this);
		}

		return dnumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dnumber} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DnumberItemProvider dnumberItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dnumber}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDnumberAdapter() {
		if (dnumberItemProvider == null) {
			dnumberItemProvider = new DnumberItemProvider(this);
		}

		return dnumberItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dparataxis} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DparataxisItemProvider dparataxisItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dparataxis}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDparataxisAdapter() {
		if (dparataxisItemProvider == null) {
			dparataxisItemProvider = new DparataxisItemProvider(this);
		}

		return dparataxisItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dpartmod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DpartmodItemProvider dpartmodItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dpartmod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDpartmodAdapter() {
		if (dpartmodItemProvider == null) {
			dpartmodItemProvider = new DpartmodItemProvider(this);
		}

		return dpartmodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dpcomp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DpcompItemProvider dpcompItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dpcomp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDpcompAdapter() {
		if (dpcompItemProvider == null) {
			dpcompItemProvider = new DpcompItemProvider(this);
		}

		return dpcompItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dpobj} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DpobjItemProvider dpobjItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dpobj}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDpobjAdapter() {
		if (dpobjItemProvider == null) {
			dpobjItemProvider = new DpobjItemProvider(this);
		}

		return dpobjItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dposs} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DpossItemProvider dpossItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dposs}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDpossAdapter() {
		if (dpossItemProvider == null) {
			dpossItemProvider = new DpossItemProvider(this);
		}

		return dpossItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dpossessive} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DpossessiveItemProvider dpossessiveItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dpossessive}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDpossessiveAdapter() {
		if (dpossessiveItemProvider == null) {
			dpossessiveItemProvider = new DpossessiveItemProvider(this);
		}

		return dpossessiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dpreconj} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DpreconjItemProvider dpreconjItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dpreconj}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDpreconjAdapter() {
		if (dpreconjItemProvider == null) {
			dpreconjItemProvider = new DpreconjItemProvider(this);
		}

		return dpreconjItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dpredet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DpredetItemProvider dpredetItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dpredet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDpredetAdapter() {
		if (dpredetItemProvider == null) {
			dpredetItemProvider = new DpredetItemProvider(this);
		}

		return dpredetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dprep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DprepItemProvider dprepItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dprep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDprepAdapter() {
		if (dprepItemProvider == null) {
			dprepItemProvider = new DprepItemProvider(this);
		}

		return dprepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dprepc} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DprepcItemProvider dprepcItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dprepc}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDprepcAdapter() {
		if (dprepcItemProvider == null) {
			dprepcItemProvider = new DprepcItemProvider(this);
		}

		return dprepcItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dprt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DprtItemProvider dprtItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dprt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDprtAdapter() {
		if (dprtItemProvider == null) {
			dprtItemProvider = new DprtItemProvider(this);
		}

		return dprtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dpunct} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DpunctItemProvider dpunctItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dpunct}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDpunctAdapter() {
		if (dpunctItemProvider == null) {
			dpunctItemProvider = new DpunctItemProvider(this);
		}

		return dpunctItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dpurpcl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DpurpclItemProvider dpurpclItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dpurpcl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDpurpclAdapter() {
		if (dpurpclItemProvider == null) {
			dpurpclItemProvider = new DpurpclItemProvider(this);
		}

		return dpurpclItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dquantmod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DquantmodItemProvider dquantmodItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dquantmod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDquantmodAdapter() {
		if (dquantmodItemProvider == null) {
			dquantmodItemProvider = new DquantmodItemProvider(this);
		}

		return dquantmodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Drcmod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DrcmodItemProvider drcmodItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Drcmod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDrcmodAdapter() {
		if (drcmodItemProvider == null) {
			drcmodItemProvider = new DrcmodItemProvider(this);
		}

		return drcmodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dref} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DrefItemProvider drefItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dref}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDrefAdapter() {
		if (drefItemProvider == null) {
			drefItemProvider = new DrefItemProvider(this);
		}

		return drefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Drel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DrelItemProvider drelItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Drel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDrelAdapter() {
		if (drelItemProvider == null) {
			drelItemProvider = new DrelItemProvider(this);
		}

		return drelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dtmod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DtmodItemProvider dtmodItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dtmod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDtmodAdapter() {
		if (dtmodItemProvider == null) {
			dtmodItemProvider = new DtmodItemProvider(this);
		}

		return dtmodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dxcomp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DxcompItemProvider dxcompItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dxcomp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDxcompAdapter() {
		if (dxcompItemProvider == null) {
			dxcompItemProvider = new DxcompItemProvider(this);
		}

		return dxcompItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Dxsubj} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DxsubjItemProvider dxsubjItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Dxsubj}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDxsubjAdapter() {
		if (dxsubjItemProvider == null) {
			dxsubjItemProvider = new DxsubjItemProvider(this);
		}

		return dxsubjItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Droot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DrootItemProvider drootItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Droot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDrootAdapter() {
		if (drootItemProvider == null) {
			drootItemProvider = new DrootItemProvider(this);
		}

		return drootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.devboost.stanford.language.Collapse} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollapseItemProvider collapseItemProvider;

	/**
	 * This creates an adapter for a {@link org.devboost.stanford.language.Collapse}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollapseAdapter() {
		if (collapseItemProvider == null) {
			collapseItemProvider = new CollapseItemProvider(this);
		}

		return collapseItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (documentItemProvider != null) documentItemProvider.dispose();
		if (sentenceItemProvider != null) sentenceItemProvider.dispose();
		if (wordItemProvider != null) wordItemProvider.dispose();
		if (ccItemProvider != null) ccItemProvider.dispose();
		if (cdItemProvider != null) cdItemProvider.dispose();
		if (dtItemProvider != null) dtItemProvider.dispose();
		if (exItemProvider != null) exItemProvider.dispose();
		if (fwItemProvider != null) fwItemProvider.dispose();
		if (inItemProvider != null) inItemProvider.dispose();
		if (jjItemProvider != null) jjItemProvider.dispose();
		if (jjrItemProvider != null) jjrItemProvider.dispose();
		if (jjsItemProvider != null) jjsItemProvider.dispose();
		if (lsItemProvider != null) lsItemProvider.dispose();
		if (mdItemProvider != null) mdItemProvider.dispose();
		if (nnItemProvider != null) nnItemProvider.dispose();
		if (nnsItemProvider != null) nnsItemProvider.dispose();
		if (nnpItemProvider != null) nnpItemProvider.dispose();
		if (nnpsItemProvider != null) nnpsItemProvider.dispose();
		if (pdtItemProvider != null) pdtItemProvider.dispose();
		if (posItemProvider != null) posItemProvider.dispose();
		if (prpItemProvider != null) prpItemProvider.dispose();
		if (prpsItemProvider != null) prpsItemProvider.dispose();
		if (rbItemProvider != null) rbItemProvider.dispose();
		if (rbrItemProvider != null) rbrItemProvider.dispose();
		if (rbsItemProvider != null) rbsItemProvider.dispose();
		if (rpItemProvider != null) rpItemProvider.dispose();
		if (symItemProvider != null) symItemProvider.dispose();
		if (toItemProvider != null) toItemProvider.dispose();
		if (uhItemProvider != null) uhItemProvider.dispose();
		if (vbItemProvider != null) vbItemProvider.dispose();
		if (vbdItemProvider != null) vbdItemProvider.dispose();
		if (vbgItemProvider != null) vbgItemProvider.dispose();
		if (vbnItemProvider != null) vbnItemProvider.dispose();
		if (vbpItemProvider != null) vbpItemProvider.dispose();
		if (vbzItemProvider != null) vbzItemProvider.dispose();
		if (wdtItemProvider != null) wdtItemProvider.dispose();
		if (wpItemProvider != null) wpItemProvider.dispose();
		if (wpsItemProvider != null) wpsItemProvider.dispose();
		if (wrbItemProvider != null) wrbItemProvider.dispose();
		if (plainTextItemProvider != null) plainTextItemProvider.dispose();
		if (dependencyItemProvider != null) dependencyItemProvider.dispose();
		if (dabbrevItemProvider != null) dabbrevItemProvider.dispose();
		if (dacompItemProvider != null) dacompItemProvider.dispose();
		if (dadvclItemProvider != null) dadvclItemProvider.dispose();
		if (dadvmodItemProvider != null) dadvmodItemProvider.dispose();
		if (dagentItemProvider != null) dagentItemProvider.dispose();
		if (damodItemProvider != null) damodItemProvider.dispose();
		if (dapposItemProvider != null) dapposItemProvider.dispose();
		if (dattrItemProvider != null) dattrItemProvider.dispose();
		if (dauxItemProvider != null) dauxItemProvider.dispose();
		if (dauxpassItemProvider != null) dauxpassItemProvider.dispose();
		if (dccItemProvider != null) dccItemProvider.dispose();
		if (dccompItemProvider != null) dccompItemProvider.dispose();
		if (dcomplmItemProvider != null) dcomplmItemProvider.dispose();
		if (dconjItemProvider != null) dconjItemProvider.dispose();
		if (dcopItemProvider != null) dcopItemProvider.dispose();
		if (dcsubjItemProvider != null) dcsubjItemProvider.dispose();
		if (dcsubjpassItemProvider != null) dcsubjpassItemProvider.dispose();
		if (ddepItemProvider != null) ddepItemProvider.dispose();
		if (ddetItemProvider != null) ddetItemProvider.dispose();
		if (ddobjItemProvider != null) ddobjItemProvider.dispose();
		if (dexplItemProvider != null) dexplItemProvider.dispose();
		if (dinfmodItemProvider != null) dinfmodItemProvider.dispose();
		if (diobjItemProvider != null) diobjItemProvider.dispose();
		if (dmarkItemProvider != null) dmarkItemProvider.dispose();
		if (dmweItemProvider != null) dmweItemProvider.dispose();
		if (dnegItemProvider != null) dnegItemProvider.dispose();
		if (dnnItemProvider != null) dnnItemProvider.dispose();
		if (dnpadvmodItemProvider != null) dnpadvmodItemProvider.dispose();
		if (dnsubjItemProvider != null) dnsubjItemProvider.dispose();
		if (dnsubjpassItemProvider != null) dnsubjpassItemProvider.dispose();
		if (dnumItemProvider != null) dnumItemProvider.dispose();
		if (dnumberItemProvider != null) dnumberItemProvider.dispose();
		if (dparataxisItemProvider != null) dparataxisItemProvider.dispose();
		if (dpartmodItemProvider != null) dpartmodItemProvider.dispose();
		if (dpcompItemProvider != null) dpcompItemProvider.dispose();
		if (dpobjItemProvider != null) dpobjItemProvider.dispose();
		if (dpossItemProvider != null) dpossItemProvider.dispose();
		if (dpossessiveItemProvider != null) dpossessiveItemProvider.dispose();
		if (dpreconjItemProvider != null) dpreconjItemProvider.dispose();
		if (dpredetItemProvider != null) dpredetItemProvider.dispose();
		if (dprepItemProvider != null) dprepItemProvider.dispose();
		if (dprepcItemProvider != null) dprepcItemProvider.dispose();
		if (dprtItemProvider != null) dprtItemProvider.dispose();
		if (dpunctItemProvider != null) dpunctItemProvider.dispose();
		if (dpurpclItemProvider != null) dpurpclItemProvider.dispose();
		if (dquantmodItemProvider != null) dquantmodItemProvider.dispose();
		if (drcmodItemProvider != null) drcmodItemProvider.dispose();
		if (drefItemProvider != null) drefItemProvider.dispose();
		if (drelItemProvider != null) drelItemProvider.dispose();
		if (dtmodItemProvider != null) dtmodItemProvider.dispose();
		if (dxcompItemProvider != null) dxcompItemProvider.dispose();
		if (dxsubjItemProvider != null) dxsubjItemProvider.dispose();
		if (drootItemProvider != null) drootItemProvider.dispose();
		if (collapseItemProvider != null) collapseItemProvider.dispose();
	}

}
