<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="annPetrinet"
    nsURI="http://www-st.inf.tu-dresden.de/tornado2/textual_rules/test/annPetrinet"
    nsPrefix="annPetrinet">
  <eClassifiers xsi:type="ecore:EClass" name="APetriNet" eSuperTypes="../../de.tudresden.tornado2.textual_rules.test.rule_derivation/metamodel/rule_derivation.ecore#//IAnnotation ../../org.emftext.language.petrinet/metamodel/petrinet.ecore#//XPetriNet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.petrinet/metamodel/petrinet.ecore#//PetriNet"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AArc" eSuperTypes="../../de.tudresden.tornado2.textual_rules.test.rule_derivation/metamodel/rule_derivation.ecore#//IAnnotation ../../org.emftext.language.petrinet/metamodel/petrinet.ecore#//XArc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.petrinet/metamodel/petrinet.ecore#//Arc"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANode" eSuperTypes="../../de.tudresden.tornado2.textual_rules.test.rule_derivation/metamodel/rule_derivation.ecore#//IAnnotation ../../org.emftext.language.petrinet/metamodel/petrinet.ecore#//XNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.petrinet/metamodel/petrinet.ecore#//Node"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AToken" eSuperTypes="../../de.tudresden.tornado2.textual_rules.test.rule_derivation/metamodel/rule_derivation.ecore#//IAnnotation ../../org.emftext.language.petrinet/metamodel/petrinet.ecore#//XToken">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.petrinet/metamodel/petrinet.ecore#//Token"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
