BASE <asd://lol.asd.as> PREFIX aa:<http:lol.asd>
SELECT DISTINCT ?a $b ?casd_a 
FROM NAMED a:b
FROM <http:lol.asd>
WHERE { ?asd a $a,?b;a $c,?d;;; . ?asd <lol> $a,?b
FILTER ()
OPTIONAL {}
GRAPH <lol> {}
{} UNION {}
}
ORDER BY $b ASC ( ) LIMIT 2 OFFSET 1