<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="manifest"
    nsURI="http://www.emftext.org/language/manifest" nsPrefix="manifest">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Directive" eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="token" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="argument" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="token" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="argument" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" lowerBound="1" upperBound="-1"
        eType="#//PathExtended" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathExtended">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Manifest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manifestVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleActivationPolicy"
        eType="#//BundleActivationPolicy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleActivator" eType="#//BundleActivator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleCategory" eType="#//BundleCategory"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleClassPath" eType="#//BundleClassPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleContactAddress" eType="#//BundleContactAddress"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleCopyright" eType="#//BundleCopyright"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleDescription" eType="#//BundleDescription"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleDocURL" eType="#//BundleDocURL"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleIcon" eType="#//BundleIcon"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleLicense" eType="#//BundleLicense"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleLocalization" eType="#//BundleLocalization"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleManifestVersion"
        eType="#//BundleManifestVersion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleName" eType="#//BundleName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleNativeCode" eType="#//BundleNativeCode"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleRequiredExecutionEnvironment"
        eType="#//BundleRequiredExecutionEnvironment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleSymbolicName" lowerBound="1"
        eType="#//BundleSymbolicName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleUpdateLocation" eType="#//BundleUpdateLocation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleVendor" eType="#//BundleVendor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleVersion" eType="#//BundleVersion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicImportPackage" eType="#//DynamicImportPackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exportPackage" eType="#//ExportPackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragmentHost" eType="#//FragmentHost"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importPackage" eType="#//ImportPackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requireBundle" eType="#//RequireBundle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eclipseLazyStart" eType="#//EclipseLazyStart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importBundle" eType="#//ImportBundle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importLibrary" eType="#//ImportLibrary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includeResource" eType="#//IncludeResource"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleScope" eType="#//ModuleScope"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleType" eType="#//ModuleType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privatePackage" eType="#//PrivatePackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webContextPath" eType="#//WebContextPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webDispatcherServletUrlPatterns"
        eType="#//WebDispatcherServletUrlPatterns" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webFilterMappings" eType="#//WebFilterMappings"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleActivationPolicy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="directive" upperBound="-1"
        eType="#//Directive" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleActivator" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleCategory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleClassPath">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" lowerBound="1" upperBound="-1"
        eType="#//Entry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleContactAddress" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleCopyright" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleDescription" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleDocURL" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleIcon">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleLicense">
    <eStructuralFeatures xsi:type="ecore:EReference" name="license" lowerBound="1"
        upperBound="-1" eType="#//License" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="License">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="licenseAttr" upperBound="-1"
        eType="#//LicenseAttr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LicenseAttr" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Description" eSuperTypes="#//LicenseAttr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//LicenseAttr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleLocalization" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleManifestVersion" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleName" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleNativeCode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nativeCode" lowerBound="1"
        upperBound="-1" eType="#//NativeCode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NativeCode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" lowerBound="1" upperBound="-1"
        eType="#//Path" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        upperBound="-1" eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleRequiredExecutionEnvironment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eeName" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleSymbolicName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolicName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleUpdateLocation" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleVendor" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleVersion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="major" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="micro" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicImportPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicDescription" lowerBound="1"
        upperBound="-1" eType="#//DynamicDescription" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wildcardName" lowerBound="1"
        upperBound="-1" eType="#//WildcardName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WildcardName">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageName" lowerBound="1"
        eType="#//PackageName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageName" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExportPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="export" lowerBound="1"
        upperBound="-1" eType="#//Export" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Export">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageName" lowerBound="1"
        upperBound="-1" eType="#//PackageName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FragmentHost">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolicName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="import" lowerBound="1"
        upperBound="-1" eType="#//Import" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageName" lowerBound="1"
        upperBound="-1" eType="#//PackageName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequireBundle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requireBundleDescription"
        lowerBound="1" upperBound="-1" eType="#//RequireBundleDescription" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequireBundleDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolicName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EclipseLazyStart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportBundle" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImportLibrary" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="IncludeResource" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleScope" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleType" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrivatePackage" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="WebContextPath" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="WebDispatcherServletUrlPatterns" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="WebFilterMappings" eSuperTypes="#//NamedElement"/>
</ecore:EPackage>
