/*******************************************************************************
 * Copyright (C) 2012
 * The Stanford Natural Language Processing Group 
 * http://nlp.stanford.edu/
 * This Eclipse plugin matches the Stanford CoreNLP version 1.3.3
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 ******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. TregexParserConstants.java */
package edu.stanford.nlp.trees.tregex;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface TregexParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RELATION = 4;
  /** RegularExpression Id. */
  int REL_W_STR_ARG = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int IDENTIFIER = 7;
  /** RegularExpression Id. */
  int BLANK = 8;
  /** RegularExpression Id. */
  int REGEX = 9;
  /** RegularExpression Id. */
  int VARNAME = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<RELATION>",
    "<REL_W_STR_ARG>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "\"__\"",
    "<REGEX>",
    "<VARNAME>",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\"@\"",
    "\"#\"",
    "\"%\"",
    "\"=\"",
    "\"~\"",
    "\"|\"",
    "\"&\"",
    "\"?\"",
    "\"[\"",
    "\"]\"",
  };

}
