<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="java_templates"
    nsURI="http://www.emftext.org/language/java_templates" nsPrefix="java_templates">
  <eClassifiers xsi:type="ecore:EClass" name="JavaTemplate" eSuperTypes="../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//Template">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//containers/JavaRoot"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfAnnotationParameter" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//annotations/AnnotationParameter ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//annotations/AnnotationParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfExpression" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//expressions/Expression ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//expressions/Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfArrayInitializationValue" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//arrays/ArrayInitializationValue ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//arrays/ArrayInitializationValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForArrayInitializationValue" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//arrays/ArrayInitializationValue ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//arrays/ArrayInitializationValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForExpression" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//expressions/Expression ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//expressions/Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfTypeReference" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//types/TypeReference ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//types/TypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForTypeReference" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//types/TypeReference ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//types/TypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfConcreteClassifier" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//classifiers/ConcreteClassifier ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//classifiers/ConcreteClassifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForConcreteClassifier" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//classifiers/ConcreteClassifier ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//classifiers/ConcreteClassifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfConditionalExpressionChild" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//expressions/ConditionalExpressionChild ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//expressions/ConditionalExpressionChild"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfTypeArgument" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//generics/TypeArgument ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//generics/TypeArgument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForTypeArgument" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//generics/TypeArgument ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//generics/TypeArgument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfImport" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//imports/Import ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//imports/Import"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForImport" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//imports/Import ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//imports/Import"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfSelf" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//literals/Self ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//literals/Self"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfMember" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//members/Member ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//members/Member"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForMember" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//members/Member ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//members/Member"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfAnnotationInstanceOrModifier" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//modifiers/AnnotationInstanceOrModifier ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//modifiers/AnnotationInstanceOrModifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForAnnotationInstanceOrModifier" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//modifiers/AnnotationInstanceOrModifier ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//modifiers/AnnotationInstanceOrModifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfModifier" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//modifiers/Modifier ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//modifiers/Modifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForModifier" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//modifiers/Modifier ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//modifiers/Modifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfParameter" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//parameters/Parameter ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//parameters/Parameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForParameter" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//parameters/Parameter ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//parameters/Parameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfReference" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//references/Reference ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//references/Reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfReferenceableElement" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//references/ReferenceableElement ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//references/ReferenceableElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//statements/Statement ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//statements/Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//statements/Statement ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//statements/Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfForLoopInitializer" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//statements/ForLoopInitializer ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//statements/ForLoopInitializer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfSwitchCase" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//statements/SwitchCase ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//statements/SwitchCase"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForSwitchCase" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//statements/SwitchCase ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//statements/SwitchCase"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
