<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="annProject"
    nsURI="http://www-st.inf.tu-dresden.de/tornado2/textual_rules/test/annProject"
    nsPrefix="annProject">
  <eClassifiers xsi:type="ecore:EClass" name="AProject" eSuperTypes="../../de.tudresden.tornado2.textual_rules.test.rule_derivation/metamodel/rule_derivation.ecore#//IAnnotation ../../org.emftext.language.project/metamodel/project.ecore#//XProject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.project/metamodel/project.ecore#//Project"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AComponent" eSuperTypes="../../de.tudresden.tornado2.textual_rules.test.rule_derivation/metamodel/rule_derivation.ecore#//IAnnotation ../../org.emftext.language.project/metamodel/project.ecore#//XComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.project/metamodel/project.ecore#//Component"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ATrain" eSuperTypes="../../de.tudresden.tornado2.textual_rules.test.rule_derivation/metamodel/rule_derivation.ecore#//IAnnotation ../../org.emftext.language.project/metamodel/project.ecore#//XTrain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.project/metamodel/project.ecore#//Train"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APort" eSuperTypes="../../de.tudresden.tornado2.textual_rules.test.rule_derivation/metamodel/rule_derivation.ecore#//IAnnotation ../../org.emftext.language.project/metamodel/project.ecore#//XPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.project/metamodel/project.ecore#//Port"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AConnection" eSuperTypes="../../de.tudresden.tornado2.textual_rules.test.rule_derivation/metamodel/rule_derivation.ecore#//IAnnotation ../../org.emftext.language.project/metamodel/project.ecore#//XConnnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.project/metamodel/project.ecore#//Connection"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
