<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="c_sharp"
    nsURI="http://www.emftext.org/c_sharp" nsPrefix="c_sharp">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceOrTypeName">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" lowerBound="1" upperBound="-1"
        eType="#//NamespaceOrTypeNamePart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceOrTypeNamePart" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Modifier" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abstract" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Extern" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Internal" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="New" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="OverrideModifier" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Private" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Protected" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Public" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReadOnly" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sealed" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Static" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unsafe" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Virtual" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Volatile" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usingDirectives" upperBound="-1"
        eType="#//UsingDirective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceMemberDeclaration"
        upperBound="-1" eType="#//NamespaceMemberDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsingDirective" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceOrTypeName" lowerBound="1"
        eType="#//NamespaceOrTypeName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceMemberDeclaration" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="#//NamespaceMemberDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceName" lowerBound="1"
        eType="#//NamespaceOrTypeName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceBody" lowerBound="1"
        eType="#//NamespaceBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usingDirectives" upperBound="-1"
        eType="#//UsingDirective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceMemberDeclaration"
        upperBound="-1" eType="#//NamespaceMemberDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" abstract="true" eSuperTypes="#//NamespaceMemberDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//TypeDeclaration #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" upperBound="-1"
        eType="#//Modifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classMemberDeclarations"
        upperBound="-1" eType="#//ClassMemberDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassMemberDeclaration" abstract="true"/>
</ecore:EPackage>
