<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="c_sharp"
    nsURI="http://www.emftext.org/c_sharp" nsPrefix="c_sharp">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceOrTypeName">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" lowerBound="1" upperBound="-1"
        eType="#//NamespaceOrTypeNamePart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceOrTypeNamePart" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Modifier" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abstract" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Extern" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Internal" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="New" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="OverrideModifier" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Private" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Protected" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Public" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReadOnly" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sealed" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Static" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unsafe" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Virtual" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Volatile" eSuperTypes="#//Modifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Decimal" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bool" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SByte" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Byte" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Short" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="UShort" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Int" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="UInt" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Long" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ULong" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Char" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Double" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceType" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassOrInterfaceOrDelegateOrEnumType"
      eSuperTypes="#//ReferenceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceOrTypeName" lowerBound="1"
        eType="#//NamespaceOrTypeName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usingDirectives" upperBound="-1"
        eType="#//UsingDirective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceMemberDeclaration"
        upperBound="-1" eType="#//NamespaceMemberDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsingDirective" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceOrTypeName" lowerBound="1"
        eType="#//NamespaceOrTypeName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceMemberDeclaration" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="#//NamespaceMemberDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceName" lowerBound="1"
        eType="#//NamespaceOrTypeName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceBody" lowerBound="1"
        eType="#//NamespaceBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usingDirectives" upperBound="-1"
        eType="#//UsingDirective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceMemberDeclaration"
        upperBound="-1" eType="#//NamespaceMemberDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" abstract="true" eSuperTypes="#//NamespaceMemberDeclaration #//ClassMemberDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//TypeDeclaration #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" upperBound="-1"
        eType="#//Modifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classBase" eType="#//ClassBase"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classMemberDeclarations"
        upperBound="-1" eType="#//ClassMemberDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" lowerBound="1" upperBound="-1"
        eType="#//ClassOrInterfaceOrDelegateOrEnumType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassMemberDeclaration" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//ClassMemberDeclaration #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" upperBound="-1"
        eType="#//Modifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceType" eType="#//ClassOrInterfaceOrDelegateOrEnumType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" lowerBound="1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclarationStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVariableDeclaration"
        eType="#//LocalVariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localConstantDeclaration"
        eType="#//LocalConstantDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="IterationStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="JumpStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TryStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CheckedStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UncheckedStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LockStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UsingStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FixedStatement" eSuperTypes="#//EmbeddedStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVariableDeclarator"
        lowerBound="1" eType="#//LocalVariableDeclarator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariableDeclarator" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVariableInitializer"
        eType="#//LocalVariableInitializer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariableInitializer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalConstantDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constantDeclarators" eType="#//ConstantDeclarators"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantDeclarators">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constantDeclarator" eType="#//ConstantDeclarator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantDeclarator" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment"/>
</ecore:EPackage>
