/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package org.emftext.language.bibtex.resource.bib.grammar;

public class BibGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public static class Rule extends org.emftext.language.bibtex.resource.bib.grammar.BibSyntaxElement {
		
		private final org.eclipse.emf.ecore.EClass metaclass;
		
		public Rule(org.eclipse.emf.ecore.EClass metaclass, org.emftext.language.bibtex.resource.bib.grammar.BibChoice choice, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality cardinality) {
			super(cardinality, new org.emftext.language.bibtex.resource.bib.grammar.BibSyntaxElement[] {choice});
			this.metaclass = metaclass;
		}
		
		public org.eclipse.emf.ecore.EClass getMetaclass() {
			return metaclass;
		}
		
		public org.emftext.language.bibtex.resource.bib.grammar.BibChoice getDefinition() {
			return (org.emftext.language.bibtex.resource.bib.grammar.BibChoice) getChildren()[0];
		}
	}
	
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getBibliography().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.BIBLIOGRAPHY__ENTRIES), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.STAR, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_0_0_0);
	public final static Rule BIB_0 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getBibliography(), BIB_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder BIB_1_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getBibtexKeyField().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.BIBTEX_KEY_FIELD__VALUE), "TEXT", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_1_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_1_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_1_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_1_0_0);
	public final static Rule BIB_1 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getBibtexKeyField(), BIB_1_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_2_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("title", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_2_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("=", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace BIB_2_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace(1, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder BIB_2_0_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getTitleField().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.TITLE_FIELD__VALUE), "QUOTED_34_34", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_2_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_2_0_0_0, BIB_2_0_0_1, BIB_2_0_0_2, BIB_2_0_0_3);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_2_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_2_0_0);
	public final static Rule BIB_2 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getTitleField(), BIB_2_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_3_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("booktitle", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_3_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("=", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace BIB_3_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace(1, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder BIB_3_0_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getBookTitleField().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.BOOK_TITLE_FIELD__VALUE), "QUOTED_34_34", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_3_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_3_0_0_0, BIB_3_0_0_1, BIB_3_0_0_2, BIB_3_0_0_3);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_3_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_3_0_0);
	public final static Rule BIB_3 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getBookTitleField(), BIB_3_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_4_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("year", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_4_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("=", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace BIB_4_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace(1, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_4_0_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("{", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder BIB_4_0_0_4 = new org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getYearField().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.YEAR_FIELD__VALUE), "YEAR", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_4_0_0_5 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("}", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_4_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_4_0_0_0, BIB_4_0_0_1, BIB_4_0_0_2, BIB_4_0_0_3, BIB_4_0_0_4, BIB_4_0_0_5);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_4_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_4_0_0);
	public final static Rule BIB_4 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getYearField(), BIB_4_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_5_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("author", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_5_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("=", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace BIB_5_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace(1, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_5_0_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("{", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_5_0_0_4 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getAuthorField().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.AUTHOR_FIELD__AUTHORS), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_5_0_0_5_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("and", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_5_0_0_5_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getAuthorField().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.AUTHOR_FIELD__AUTHORS), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_5_0_0_5_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_5_0_0_5_0_0_0, BIB_5_0_0_5_0_0_1);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_5_0_0_5_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_5_0_0_5_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_5_0_0_5 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_5_0_0_5_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.STAR);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_5_0_0_6 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("}", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_5_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_5_0_0_0, BIB_5_0_0_1, BIB_5_0_0_2, BIB_5_0_0_3, BIB_5_0_0_4, BIB_5_0_0_5, BIB_5_0_0_6);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_5_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_5_0_0);
	public final static Rule BIB_5 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getAuthorField(), BIB_5_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder BIB_6_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getAuthor().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.AUTHOR__FIRST_NAME), "TEXT", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder BIB_6_0_0_1_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getAuthor().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.AUTHOR__SECOND_NAME), "TEXT", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_6_0_0_1_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_6_0_0_1_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_6_0_0_1_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_6_0_0_1_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_6_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_6_0_0_1_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.QUESTIONMARK);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder BIB_6_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getAuthor().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.AUTHOR__LAST_NAME), "TEXT", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_6_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_6_0_0_0, BIB_6_0_0_1, BIB_6_0_0_2);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_6_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_6_0_0);
	public final static Rule BIB_6 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getAuthor(), BIB_6_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_7_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("journal", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_7_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("=", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace BIB_7_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace(1, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_7_0_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("{", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder BIB_7_0_0_4 = new org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getJournalField().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.JOURNAL_FIELD__VALUE), "TEXT", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_7_0_0_5 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("}", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_7_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_7_0_0_0, BIB_7_0_0_1, BIB_7_0_0_2, BIB_7_0_0_3, BIB_7_0_0_4, BIB_7_0_0_5);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_7_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_7_0_0);
	public final static Rule BIB_7 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getJournalField(), BIB_7_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_8_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("volume", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_8_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("=", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace BIB_8_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace(1, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_8_0_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("{", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder BIB_8_0_0_4 = new org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getVolumeField().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.VOLUME_FIELD__VALUE), "INTEGER", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_8_0_0_5 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("}", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_8_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_8_0_0_0, BIB_8_0_0_1, BIB_8_0_0_2, BIB_8_0_0_3, BIB_8_0_0_4, BIB_8_0_0_5);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_8_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_8_0_0);
	public final static Rule BIB_8 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getVolumeField(), BIB_8_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_9_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("pages", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_9_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("=", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace BIB_9_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace(1, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_9_0_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("{", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_9_0_0_4 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getPageField().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.PAGE_FIELD__FROM_PAGE), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_9_0_0_5_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("--", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_9_0_0_5_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getPageField().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.PAGE_FIELD__TO_PAGE), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_9_0_0_5_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_9_0_0_5_0_0_0, BIB_9_0_0_5_0_0_1);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_9_0_0_5_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_9_0_0_5_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_9_0_0_5 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_9_0_0_5_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.QUESTIONMARK);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_9_0_0_6 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("}", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_9_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_9_0_0_0, BIB_9_0_0_1, BIB_9_0_0_2, BIB_9_0_0_3, BIB_9_0_0_4, BIB_9_0_0_5, BIB_9_0_0_6);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_9_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_9_0_0);
	public final static Rule BIB_9 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getPageField(), BIB_9_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder BIB_10_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibPlaceholder(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getPage().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.PAGE__VALUE), "INTEGER", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_10_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_10_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_10_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_10_0_0);
	public final static Rule BIB_10 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getPage(), BIB_10_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_11_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("@INPROCEEDINGS", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_11_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("{", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak BIB_11_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 1);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_11_0_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getInProceedingsEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.IN_PROCEEDINGS_ENTRY__BIBTEX_KEY), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace BIB_11_0_0_4 = new org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace(1, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_11_0_0_5_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword(",", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak BIB_11_0_0_5_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 1);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_11_0_0_5_0_0_2_0_0_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getInProceedingsEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.IN_PROCEEDINGS_ENTRY__TITLE), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_11_0_0_5_0_0_2_0_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_0_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_11_0_0_5_0_0_2_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_11_0_0_5_0_0_2_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_11_0_0_5_0_0_2_0_0_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_11_0_0_5_0_0_2_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_11_0_0_5_0_0_2_0_1_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getInProceedingsEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.IN_PROCEEDINGS_ENTRY__BOOK_TITLE), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_11_0_0_5_0_0_2_0_1_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_1_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_11_0_0_5_0_0_2_0_1_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_1_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_11_0_0_5_0_0_2_0_1_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_11_0_0_5_0_0_2_0_1_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_11_0_0_5_0_0_2_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_1_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_11_0_0_5_0_0_2_0_2_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getInProceedingsEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.IN_PROCEEDINGS_ENTRY__YEAR), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_11_0_0_5_0_0_2_0_2_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_2_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_11_0_0_5_0_0_2_0_2_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_2_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_11_0_0_5_0_0_2_0_2_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_11_0_0_5_0_0_2_0_2_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_11_0_0_5_0_0_2_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_2_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_11_0_0_5_0_0_2_0_3_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getInProceedingsEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.IN_PROCEEDINGS_ENTRY__AUTHOR), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_11_0_0_5_0_0_2_0_3_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_3_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_11_0_0_5_0_0_2_0_3_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_3_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_11_0_0_5_0_0_2_0_3_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_11_0_0_5_0_0_2_0_3_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_11_0_0_5_0_0_2_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_3_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_11_0_0_5_0_0_2_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_2_0_0, BIB_11_0_0_5_0_0_2_0_1, BIB_11_0_0_5_0_0_2_0_2, BIB_11_0_0_5_0_0_2_0_3);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_11_0_0_5_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_11_0_0_5_0_0_2_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_11_0_0_5_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0_0, BIB_11_0_0_5_0_0_1, BIB_11_0_0_5_0_0_2);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_11_0_0_5_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_5_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_11_0_0_5 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_11_0_0_5_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.PLUS);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak BIB_11_0_0_6 = new org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 1);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_11_0_0_7 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("}", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_11_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0_0, BIB_11_0_0_1, BIB_11_0_0_2, BIB_11_0_0_3, BIB_11_0_0_4, BIB_11_0_0_5, BIB_11_0_0_6, BIB_11_0_0_7);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_11_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_11_0_0);
	public final static Rule BIB_11 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getInProceedingsEntry(), BIB_11_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_12_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("@ARTICLE", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_12_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("{", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak BIB_12_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 1);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_12_0_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getArticleEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.ARTICLE_ENTRY__BIBTEX_KEY), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace BIB_12_0_0_4 = new org.emftext.language.bibtex.resource.bib.grammar.BibWhiteSpace(1, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_12_0_0_5_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword(",", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak BIB_12_0_0_5_0_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 1);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_12_0_0_5_0_0_2_0_0_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getArticleEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.ARTICLE_ENTRY__TITLE), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_0_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_12_0_0_5_0_0_2_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_12_0_0_5_0_0_2_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_12_0_0_5_0_0_2_0_0_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_12_0_0_5_0_0_2_0_1_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getArticleEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.ARTICLE_ENTRY__JOURNAL), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_1_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_1_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_12_0_0_5_0_0_2_0_1_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_1_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_12_0_0_5_0_0_2_0_1_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_12_0_0_5_0_0_2_0_1_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_1 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_1_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_12_0_0_5_0_0_2_0_2_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getArticleEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.ARTICLE_ENTRY__VOLUME), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_2_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_2_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_12_0_0_5_0_0_2_0_2_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_2_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_12_0_0_5_0_0_2_0_2_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_12_0_0_5_0_0_2_0_2_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_2_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_12_0_0_5_0_0_2_0_3_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getArticleEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.ARTICLE_ENTRY__YEAR), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_3_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_3_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_12_0_0_5_0_0_2_0_3_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_3_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_12_0_0_5_0_0_2_0_3_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_12_0_0_5_0_0_2_0_3_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_3 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_3_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_12_0_0_5_0_0_2_0_4_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getArticleEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.ARTICLE_ENTRY__AUTHOR), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_4_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_4_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_12_0_0_5_0_0_2_0_4_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_4_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_12_0_0_5_0_0_2_0_4_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_12_0_0_5_0_0_2_0_4_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_4 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_4_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibContainment BIB_12_0_0_5_0_0_2_0_5_0_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibContainment(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getArticleEntry().getEStructuralFeature(org.emftext.language.bibtex.BibtexPackage.ARTICLE_ENTRY__PAGES), org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_5_0_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_5_0_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_12_0_0_5_0_0_2_0_5_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_5_0_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_12_0_0_5_0_0_2_0_5_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_12_0_0_5_0_0_2_0_5_0_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0_2_0_5 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_5_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_12_0_0_5_0_0_2_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_2_0_0, BIB_12_0_0_5_0_0_2_0_1, BIB_12_0_0_5_0_0_2_0_2, BIB_12_0_0_5_0_0_2_0_3, BIB_12_0_0_5_0_0_2_0_4, BIB_12_0_0_5_0_0_2_0_5);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_12_0_0_5_0_0_2 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_12_0_0_5_0_0_2_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0_5_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0_0, BIB_12_0_0_5_0_0_1, BIB_12_0_0_5_0_0_2);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_12_0_0_5_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_5_0_0);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibCompound BIB_12_0_0_5 = new org.emftext.language.bibtex.resource.bib.grammar.BibCompound(BIB_12_0_0_5_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.PLUS);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak BIB_12_0_0_6 = new org.emftext.language.bibtex.resource.bib.grammar.BibLineBreak(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, 1);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibKeyword BIB_12_0_0_7 = new org.emftext.language.bibtex.resource.bib.grammar.BibKeyword("}", org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibSequence BIB_12_0_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibSequence(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0_0, BIB_12_0_0_1, BIB_12_0_0_2, BIB_12_0_0_3, BIB_12_0_0_4, BIB_12_0_0_5, BIB_12_0_0_6, BIB_12_0_0_7);
	public final static org.emftext.language.bibtex.resource.bib.grammar.BibChoice BIB_12_0 = new org.emftext.language.bibtex.resource.bib.grammar.BibChoice(org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE, BIB_12_0_0);
	public final static Rule BIB_12 = new Rule(org.emftext.language.bibtex.BibtexPackage.eINSTANCE.getArticleEntry(), BIB_12_0, org.emftext.language.bibtex.resource.bib.grammar.BibCardinality.ONE);
}
