<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="template_concepts"
    nsURI="http://www.emftext.org/language/template_concepts" nsPrefix="template_concepts">
  <eClassifiers xsi:type="ecore:EClass" name="ForLoop" abstract="true" eSuperTypes="#//MultiBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collection" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfCondition" abstract="true" eSuperTypes="#//SingleBody #//MultiBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Placeholder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiBody" abstract="true" eSuperTypes="#//Body"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleBody" abstract="true" eSuperTypes="#//Body"/>
  <eClassifiers xsi:type="ecore:EClass" name="Body" abstract="true"/>
</ecore:EPackage>
