<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rolecore"
    nsURI="http://www.emftext.org/language/rolecore" nsPrefix="rolecore">
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedBy" lowerBound="1"
        eType="#//CoreClass" eOpposite="#//CoreClass/plays"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreClass" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plays" upperBound="-1"
        eType="#//Role" eOpposite="#//Role/playedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" eType="#//CoreClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RCPackage" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coreClasses" upperBound="-1"
        eType="#//CoreClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
