SYNTAXDEF uml
FOR <http://www.eclipse.org/uml2/2.1.0/UML>
START StateMachine

TOKENS{
		DEFINE COMMENT$'//'(~('\n'|'\r'))*$;
		DEFINE INTEGER$('-')?('1'..'9')('0'..'9')*|'0'$;
		DEFINE FLOAT$('-')?(('1'..'9') ('0'..'9')* | '0') '.' ('0'..'9')+ $;
}

RULES{
		
		StateMachine	::= "StateMachine" name['"','"'] region ;
		
		Region 			::= ( subvertex ";")*;
		
		State 			::= "state" name['"','"'] "{"
							("entry" ":" entry)?
							("exit" ":" exit)?
							"do" ":" doActivity							
							"}";
							
		FinalState		::= "final" "state"	name['"','"'] "{"
							("entry" ":" entry)?
							("exit" ":" exit)?
							"do" ":" doActivity							
							"}"; 					
							
		Transition		::= "transition" 
							"from" source[]
							"to" target[]
							"when" trigger
							"do" effect;
							
		Trigger			::= name['"','"']; 
		
		Activity		::= name['"','"'];
							
							
		
//		Region::=isLeaf[]? "Region"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "elementImport"  ":" elementImport | "packageImport"  ":" packageImport | "ownedRule"  ":" ownedRule | "member"  ":" member[]| "importedMember"  ":" importedMember[]| "ownedMember"  ":" ownedMember[]| "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "subvertex"  ":" subvertex | "transition"  ":" transition | "state"  ":" state[]| "extendedRegion"  ":" extendedRegion[]| "stateMachine"  ":" stateMachine[] )* "}"  ;
		
//		Transition::=isLeaf[]? "Transition"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "elementImport"  ":" elementImport | "packageImport"  ":" packageImport | "ownedRule"  ":" ownedRule | "member"  ":" member[]| "importedMember"  ":" importedMember[]| "ownedMember"  ":" ownedMember[]| "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "kind"  ":" kind[]| "container"  ":" container[]| "redefinedTransition"  ":" redefinedTransition[]| "guard"  ":" guard[]| "effect"  ":" effect | "trigger"  ":" trigger | "target"  ":" target[]| "source"  ":" source[] )* "}"  ;
		
//		Trigger::= "Trigger"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "event"  ":" event[]| "port"  ":" port[] )* "}"  ;
		
		
//		ConnectionPointReference::= "ConnectionPointReference"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "incoming"  ":" incoming[]| "outgoing"  ":" outgoing[]| "container"  ":" container[]| "entry"  ":" entry[]| "exit"  ":" exit[]| "state"  ":" state[] )* "}"  ;
		
//		Pseudostate::= "Pseudostate"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "incoming"  ":" incoming[]| "outgoing"  ":" outgoing[]| "container"  ":" container[]| "kind"  ":" kind[]| "stateMachine"  ":" stateMachine[]| "state"  ":" state[] )* "}"  ;
		
		
//		StructuredActivityNode::=isLeaf[]?mustIsolate[]? "StructuredActivityNode"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "inStructuredNode"  ":" inStructuredNode[]| "activity"  ":" activity[]| "outgoing"  ":" outgoing[]| "incoming"  ":" incoming[]| "inPartition"  ":" inPartition[]| "inInterruptibleRegion"  ":" inInterruptibleRegion[]| "inGroup"  ":" inGroup[]| "redefinedNode"  ":" redefinedNode[]| "handler"  ":" handler | "output"  ":" output[]| "input"  ":" input[]| "context"  ":" context[]| "localPrecondition"  ":" localPrecondition | "localPostcondition"  ":" localPostcondition | "elementImport"  ":" elementImport | "packageImport"  ":" packageImport | "ownedRule"  ":" ownedRule | "member"  ":" member[]| "importedMember"  ":" importedMember[]| "ownedMember"  ":" ownedMember[]| "subgroup"  ":" subgroup[]| "superGroup"  ":" superGroup[]| "inActivity"  ":" inActivity[]| "containedEdge"  ":" containedEdge[]| "containedNode"  ":" containedNode[]| "variable"  ":" variable | "edge"  ":" edge | "node"  ":" node  )* "}"  ;
		
//		Activity::=isLeaf[]?isAbstract[]?isActive[]?isReentrant[]?isReadOnly[]?isSingleExecution[]? "Activity"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "elementImport"  ":" elementImport | "packageImport"  ":" packageImport | "ownedRule"  ":" ownedRule | "member"  ":" member[]| "importedMember"  ":" importedMember[]| "ownedMember"  ":" ownedMember[]| "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "owningTemplateParameter"  ":" owningTemplateParameter[]| "templateParameter"  ":" templateParameter[]| "package"  ":" package[]| "templateBinding"  ":" templateBinding | "ownedTemplateSignature"  ":" ownedTemplateSignature | "generalization"  ":" generalization | "powertypeExtent"  ":" powertypeExtent[]| "feature"  ":" feature[]| "inheritedMember"  ":" inheritedMember[]| "redefinedClassifier"  ":" redefinedClassifier[]| "general"  ":" general[]| "substitution"  ":" substitution | "attribute"  ":" attribute[]| "representation"  ":" representation[]| "collaborationUse"  ":" collaborationUse | "ownedUseCase"  ":" ownedUseCase | "useCase"  ":" useCase[]| "ownedAttribute"  ":" ownedAttribute | "part"  ":" part[]| "role"  ":" role[]| "ownedConnector"  ":" ownedConnector | "ownedPort"  ":" ownedPort[]| "ownedBehavior"  ":" ownedBehavior | "classifierBehavior"  ":" classifierBehavior[]| "interfaceRealization"  ":" interfaceRealization | "ownedTrigger"  ":" ownedTrigger | "nestedClassifier"  ":" nestedClassifier | "ownedOperation"  ":" ownedOperation | "superClass"  ":" superClass[]| "ownedReception"  ":" ownedReception | "extension"  ":" extension[]| "redefinedBehavior"  ":" redefinedBehavior[]| "ownedParameter"  ":" ownedParameter | "context"  ":" context[]| "precondition"  ":" precondition[]| "postcondition"  ":" postcondition[]| "ownedParameterSet"  ":" ownedParameterSet | "specification"  ":" specification[]| "structuredNode"  ":" structuredNode[]| "variable"  ":" variable | "node"  ":" node | "edge"  ":" edge | "partition"  ":" partition[]| "group"  ":" group  )* "}"  ;
		
		
//		StateInvariant::= "StateInvariant"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "covered"  ":" covered[]| "generalOrdering"  ":" generalOrdering | "enclosingInteraction"  ":" enclosingInteraction[]| "enclosingOperand"  ":" enclosingOperand[]| "invariant"  ":" invariant  )* "}"  ;
		
		
//		CallEvent::= "CallEvent"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "owningTemplateParameter"  ":" owningTemplateParameter[]| "templateParameter"  ":" templateParameter[]| "operation"  ":" operation[] )* "}"  ;
		
//		ChangeEvent::= "ChangeEvent"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "owningTemplateParameter"  ":" owningTemplateParameter[]| "templateParameter"  ":" templateParameter[]| "changeExpression"  ":" changeExpression  )* "}"  ;
		
//		SignalEvent::= "SignalEvent"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "owningTemplateParameter"  ":" owningTemplateParameter[]| "templateParameter"  ":" templateParameter[]| "signal"  ":" signal[] )* "}"  ;
		
//		AnyReceiveEvent::= "AnyReceiveEvent"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "owningTemplateParameter"  ":" owningTemplateParameter[]| "templateParameter"  ":" templateParameter[] )* "}"  ;
		
//		ForkNode::=isLeaf[]? "ForkNode"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "inStructuredNode"  ":" inStructuredNode[]| "activity"  ":" activity[]| "outgoing"  ":" outgoing[]| "incoming"  ":" incoming[]| "inPartition"  ":" inPartition[]| "inInterruptibleRegion"  ":" inInterruptibleRegion[]| "inGroup"  ":" inGroup[]| "redefinedNode"  ":" redefinedNode[] )* "}"  ;
		
//		FlowFinalNode::=isLeaf[]? "FlowFinalNode"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "inStructuredNode"  ":" inStructuredNode[]| "activity"  ":" activity[]| "outgoing"  ":" outgoing[]| "incoming"  ":" incoming[]| "inPartition"  ":" inPartition[]| "inInterruptibleRegion"  ":" inInterruptibleRegion[]| "inGroup"  ":" inGroup[]| "redefinedNode"  ":" redefinedNode[] )* "}"  ;
		
//		CentralBufferNode::=isLeaf[]?isControlType[]? "CentralBufferNode"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "inStructuredNode"  ":" inStructuredNode[]| "activity"  ":" activity[]| "outgoing"  ":" outgoing[]| "incoming"  ":" incoming[]| "inPartition"  ":" inPartition[]| "inInterruptibleRegion"  ":" inInterruptibleRegion[]| "inGroup"  ":" inGroup[]| "redefinedNode"  ":" redefinedNode[]| "type"  ":" type[]| "ordering"  ":" ordering[]| "upperBound"  ":" upperBound | "inState"  ":" inState[]| "selection"  ":" selection[] )* "}"  ;
		
//		MergeNode::=isLeaf[]? "MergeNode"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "inStructuredNode"  ":" inStructuredNode[]| "activity"  ":" activity[]| "outgoing"  ":" outgoing[]| "incoming"  ":" incoming[]| "inPartition"  ":" inPartition[]| "inInterruptibleRegion"  ":" inInterruptibleRegion[]| "inGroup"  ":" inGroup[]| "redefinedNode"  ":" redefinedNode[] )* "}"  ;
		
//		DecisionNode::=isLeaf[]? "DecisionNode"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "inStructuredNode"  ":" inStructuredNode[]| "activity"  ":" activity[]| "outgoing"  ":" outgoing[]| "incoming"  ":" incoming[]| "inPartition"  ":" inPartition[]| "inInterruptibleRegion"  ":" inInterruptibleRegion[]| "inGroup"  ":" inGroup[]| "redefinedNode"  ":" redefinedNode[]| "decisionInput"  ":" decisionInput[] )* "}"  ;
		
//		ActivityFinalNode::=isLeaf[]? "ActivityFinalNode"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "inStructuredNode"  ":" inStructuredNode[]| "activity"  ":" activity[]| "outgoing"  ":" outgoing[]| "incoming"  ":" incoming[]| "inPartition"  ":" inPartition[]| "inInterruptibleRegion"  ":" inInterruptibleRegion[]| "inGroup"  ":" inGroup[]| "redefinedNode"  ":" redefinedNode[] )* "}"  ;
		
//		Node::=isLeaf[]?isAbstract[]?isActive[]? "Node"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "elementImport"  ":" elementImport | "packageImport"  ":" packageImport | "ownedRule"  ":" ownedRule | "member"  ":" member[]| "importedMember"  ":" importedMember[]| "ownedMember"  ":" ownedMember[]| "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "owningTemplateParameter"  ":" owningTemplateParameter[]| "templateParameter"  ":" templateParameter[]| "package"  ":" package[]| "templateBinding"  ":" templateBinding | "ownedTemplateSignature"  ":" ownedTemplateSignature | "generalization"  ":" generalization | "powertypeExtent"  ":" powertypeExtent[]| "feature"  ":" feature[]| "inheritedMember"  ":" inheritedMember[]| "redefinedClassifier"  ":" redefinedClassifier[]| "general"  ":" general[]| "substitution"  ":" substitution | "attribute"  ":" attribute[]| "representation"  ":" representation[]| "collaborationUse"  ":" collaborationUse | "ownedUseCase"  ":" ownedUseCase | "useCase"  ":" useCase[]| "ownedAttribute"  ":" ownedAttribute | "part"  ":" part[]| "role"  ":" role[]| "ownedConnector"  ":" ownedConnector | "ownedPort"  ":" ownedPort[]| "ownedBehavior"  ":" ownedBehavior | "classifierBehavior"  ":" classifierBehavior[]| "interfaceRealization"  ":" interfaceRealization | "ownedTrigger"  ":" ownedTrigger | "nestedClassifier"  ":" nestedClassifier | "ownedOperation"  ":" ownedOperation | "superClass"  ":" superClass[]| "ownedReception"  ":" ownedReception | "extension"  ":" extension[]| "deployment"  ":" deployment | "deployedElement"  ":" deployedElement[]| "nestedNode"  ":" nestedNode  )* "}"  ;
		
//		Device::=isLeaf[]?isAbstract[]?isActive[]? "Device"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "elementImport"  ":" elementImport | "packageImport"  ":" packageImport | "ownedRule"  ":" ownedRule | "member"  ":" member[]| "importedMember"  ":" importedMember[]| "ownedMember"  ":" ownedMember[]| "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "owningTemplateParameter"  ":" owningTemplateParameter[]| "templateParameter"  ":" templateParameter[]| "package"  ":" package[]| "templateBinding"  ":" templateBinding | "ownedTemplateSignature"  ":" ownedTemplateSignature | "generalization"  ":" generalization | "powertypeExtent"  ":" powertypeExtent[]| "feature"  ":" feature[]| "inheritedMember"  ":" inheritedMember[]| "redefinedClassifier"  ":" redefinedClassifier[]| "general"  ":" general[]| "substitution"  ":" substitution | "attribute"  ":" attribute[]| "representation"  ":" representation[]| "collaborationUse"  ":" collaborationUse | "ownedUseCase"  ":" ownedUseCase | "useCase"  ":" useCase[]| "ownedAttribute"  ":" ownedAttribute | "part"  ":" part[]| "role"  ":" role[]| "ownedConnector"  ":" ownedConnector | "ownedPort"  ":" ownedPort[]| "ownedBehavior"  ":" ownedBehavior | "classifierBehavior"  ":" classifierBehavior[]| "interfaceRealization"  ":" interfaceRealization | "ownedTrigger"  ":" ownedTrigger | "nestedClassifier"  ":" nestedClassifier | "ownedOperation"  ":" ownedOperation | "superClass"  ":" superClass[]| "ownedReception"  ":" ownedReception | "extension"  ":" extension[]| "deployment"  ":" deployment | "deployedElement"  ":" deployedElement[]| "nestedNode"  ":" nestedNode  )* "}"  ;
		
//		ExecutionEnvironment::=isLeaf[]?isAbstract[]?isActive[]? "ExecutionEnvironment"  "{" ( "eAnnotations"  ":" eAnnotations | "ownedElement"  ":" ownedElement[]| "owner"  ":" owner[]| "ownedComment"  ":" ownedComment | "name"  ":" name['"','"'] | "visibility"  ":" visibility[]| "qualifiedName"  ":" qualifiedName['"','"'] | "clientDependency"  ":" clientDependency[]| "namespace"  ":" namespace[]| "nameExpression"  ":" nameExpression | "elementImport"  ":" elementImport | "packageImport"  ":" packageImport | "ownedRule"  ":" ownedRule | "member"  ":" member[]| "importedMember"  ":" importedMember[]| "ownedMember"  ":" ownedMember[]| "redefinedElement"  ":" redefinedElement[]| "redefinitionContext"  ":" redefinitionContext[]| "owningTemplateParameter"  ":" owningTemplateParameter[]| "templateParameter"  ":" templateParameter[]| "package"  ":" package[]| "templateBinding"  ":" templateBinding | "ownedTemplateSignature"  ":" ownedTemplateSignature | "generalization"  ":" generalization | "powertypeExtent"  ":" powertypeExtent[]| "feature"  ":" feature[]| "inheritedMember"  ":" inheritedMember[]| "redefinedClassifier"  ":" redefinedClassifier[]| "general"  ":" general[]| "substitution"  ":" substitution | "attribute"  ":" attribute[]| "representation"  ":" representation[]| "collaborationUse"  ":" collaborationUse | "ownedUseCase"  ":" ownedUseCase | "useCase"  ":" useCase[]| "ownedAttribute"  ":" ownedAttribute | "part"  ":" part[]| "role"  ":" role[]| "ownedConnector"  ":" ownedConnector | "ownedPort"  ":" ownedPort[]| "ownedBehavior"  ":" ownedBehavior | "classifierBehavior"  ":" classifierBehavior[]| "interfaceRealization"  ":" interfaceRealization | "ownedTrigger"  ":" ownedTrigger | "nestedClassifier"  ":" nestedClassifier | "ownedOperation"  ":" ownedOperation | "superClass"  ":" superClass[]| "ownedReception"  ":" ownedReception | "extension"  ":" extension[]| "deployment"  ":" deployment | "deployedElement"  ":" deployedElement[]| "nestedNode"  ":" nestedNode  )* "}"  ;
		
			
}