package org.eclipse.uml2.uml.resource.uml;

import java.io.OutputStream;
import org.reuseware.emftextedit.runtime.resource.*;

/**
* This is the printer class used by EMFText.
* Users may implement own behavior by overriding printing methods in the printer base.
* The baseclass contains a pretty printer implementation generated by EMFText which
* is not granted to work in all cases, but should work in most cases.
*/
public class UmlPrinter extends UmlPrinterBase {

	public UmlPrinter(OutputStream o, TextResource resource) {
		super(o, resource);
	}
}
