package org.emftext.language.simple_c.resource.c;

import java.io.OutputStream;
import org.emftext.runtime.resource.*;

/**
* This is the printer class used by EMFText.
* Users may implement own behavior by overriding printing methods in the printer base.
* The baseclass contains a pretty printer implementation generated by EMFText which
* is not granted to work in all cases, but should work in most cases.
*/
public class CPrinter extends CPrinterBase {

	public CPrinter(OutputStream o, TextResource resource) {
		super(o, resource);
	}
}
