/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package org.emftext.language.prolog.resource.pl.ui;

/**
 * A CodeCompletionHelper can be used to derive completion proposals for partial
 * documents. It runs the parser generated by EMFText in a special mode (i.e., the
 * rememberExpectedElements mode). Based on the elements that are expected by the
 * parser for different regions in the document, valid proposals are computed.
 */
public class PlCodeCompletionHelper {
	
	private org.emftext.language.prolog.resource.pl.mopp.PlAttributeValueProvider attributeValueProvider = new org.emftext.language.prolog.resource.pl.mopp.PlAttributeValueProvider();
	
	private org.emftext.language.prolog.resource.pl.IPlMetaInformation metaInformation = new org.emftext.language.prolog.resource.pl.mopp.PlMetaInformation();
	
	/**
	 * Computes a set of proposals for the given document assuming the cursor is at
	 * 'cursorOffset'. The proposals are derived using the meta information, i.e., the
	 * generated language plug-in.
	 * 
	 * @param originalResource
	 * @param content the documents content
	 * @param cursorOffset
	 * 
	 * @return
	 */
	public org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal[] computeCompletionProposals(org.emftext.language.prolog.resource.pl.IPlTextResource originalResource, String content, int cursorOffset) {
		org.eclipse.emf.ecore.resource.ResourceSet resourceSet = new org.eclipse.emf.ecore.resource.impl.ResourceSetImpl();
		// the shadow resource needs the same URI because reference resolvers may use the
		// URI to resolve external references
		org.emftext.language.prolog.resource.pl.IPlTextResource resource = (org.emftext.language.prolog.resource.pl.IPlTextResource) resourceSet.createResource(originalResource.getURI());
		java.io.ByteArrayInputStream inputStream = new java.io.ByteArrayInputStream(content.getBytes());
		org.emftext.language.prolog.resource.pl.IPlMetaInformation metaInformation = resource.getMetaInformation();
		org.emftext.language.prolog.resource.pl.IPlTextParser parser = metaInformation.createParser(inputStream, null);
		org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal[] expectedElements = parseToExpectedElements(parser, resource, cursorOffset);
		if (expectedElements == null) {
			return new org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal[0];
		}
		if (expectedElements.length == 0) {
			return new org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal[0];
		}
		java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> expectedAfterCursor = java.util.Arrays.asList(getElementsExpectedAt(expectedElements, cursorOffset));
		java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> expectedBeforeCursor = java.util.Arrays.asList(getElementsExpectedAt(expectedElements, cursorOffset - 1));
		setPrefixes(expectedAfterCursor, content, cursorOffset);
		setPrefixes(expectedBeforeCursor, content, cursorOffset);
		// First, we derive all possible proposals from the set of elements that are
		// expected at the cursor position.
		java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> allProposals = new java.util.LinkedHashSet<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal>();
		java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> rightProposals = deriveProposals(expectedAfterCursor, content, resource, cursorOffset);
		java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> leftProposals = deriveProposals(expectedBeforeCursor, content, resource, cursorOffset - 1);
		removeKeywordsEndingBeforeIndex(leftProposals, cursorOffset);
		// Second, the set of left proposals (i.e., the ones before the cursor) is checked
		// for emptiness. If the set is empty, the right proposals (i.e., the ones after
		// the cursor) are also considered. If the set is not empty, the right proposal
		// are discarded, because it does not make sense to propose them until the element
		// before the cursor was completed.
		allProposals.addAll(leftProposals);
		// Count the proposals before the cursor that match the prefix
		int leftMatchingProposals = 0;
		for (org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal leftProposal : leftProposals) {
			if (leftProposal.getMatchesPrefix()) {
				leftMatchingProposals++;
			}
		}
		if (leftMatchingProposals == 0) {
			allProposals.addAll(rightProposals);
		}
		// Third, the proposals are sorted according to their relevance. Proposals that
		// matched the prefix are preferred over ones that did not. Finally, proposals are
		// sorted alphabetically.
		final java.util.List<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> sortedProposals = new java.util.ArrayList<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal>(allProposals);
		java.util.Collections.sort(sortedProposals);
		org.eclipse.emf.ecore.EObject root = null;
		if (!resource.getContents().isEmpty()) {
			root = resource.getContents().get(0);
		}
		for (org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal proposal : sortedProposals) {
			proposal.setRoot(root);
		}
		return sortedProposals.toArray(new org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal[sortedProposals.size()]);
	}
	
	public org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal[] parseToExpectedElements(org.emftext.language.prolog.resource.pl.IPlTextParser parser, org.emftext.language.prolog.resource.pl.IPlTextResource resource, int cursorOffset) {
		final java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> expectedElements = parser.parseToExpectedElements(null, resource, cursorOffset);
		if (expectedElements == null) {
			return new org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal[0];
		}
		removeDuplicateEntries(expectedElements);
		removeInvalidEntriesAtEnd(expectedElements);
		return expectedElements.toArray(new org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal[expectedElements.size()]);
	}
	
	/**
	 * Removes all expected elements that refer to the same terminal and that start at
	 * the same position.
	 */
	private void removeDuplicateEntries(java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> expectedElements) {
		int size = expectedElements.size();
		// We split the list of expected elements into buckets where each bucket contains
		// the elements that start at the same position.
		java.util.Map<Integer, java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal>> map = new java.util.LinkedHashMap<Integer, java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal>>();
		for (int i = 0; i < size; i++) {
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal elementAtIndex = expectedElements.get(i);
			int start1 = elementAtIndex.getStartExcludingHiddenTokens();
			java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> list = map.get(start1);
			if (list == null) {
				list = new java.util.ArrayList<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal>();
				map.put(start1, list);
			}
			list.add(elementAtIndex);
		}
		
		// Then, we remove all duplicate elements from each bucket individually.
		for (int position : map.keySet()) {
			java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> list = map.get(position);
			removeDuplicateEntriesFromBucket(list);
		}
		
		// After removing all duplicates, we merge the buckets.
		expectedElements.clear();
		for (int position : map.keySet()) {
			java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> list = map.get(position);
			expectedElements.addAll(list);
		}
	}
	
	/**
	 * Removes all expected elements that refer to the same terminal. Attention: This
	 * methods assumes that the given list of expected terminals contains only
	 * elements that start at the same position.
	 */
	private void removeDuplicateEntriesFromBucket(java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> expectedElements) {
		int size = expectedElements.size();
		for (int i = 0; i < size - 1; i++) {
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal elementAtIndex = expectedElements.get(i);
			org.emftext.language.prolog.resource.pl.IPlExpectedElement terminal = elementAtIndex.getTerminal();
			for (int j = i + 1; j < size;) {
				org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal elementAtNext = expectedElements.get(j);
				if (terminal.equals(elementAtNext.getTerminal())) {
					expectedElements.remove(j);
					size--;
				} else {
					j++;
				}
			}
		}
	}
	
	private void removeInvalidEntriesAtEnd(java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> expectedElements) {
		for (int i = 0; i < expectedElements.size() - 1;) {
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal elementAtIndex = expectedElements.get(i);
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal elementAtNext = expectedElements.get(i + 1);
			if (elementAtIndex.getStartExcludingHiddenTokens() == elementAtNext.getStartExcludingHiddenTokens() && shouldRemove(elementAtIndex.getFollowSetID(), elementAtNext.getFollowSetID())) {
				expectedElements.remove(i + 1);
			} else {
				i++;
			}
		}
	}
	
	private boolean shouldRemove(int followSetID1, int followSetID2) {
		return followSetID1 != followSetID2;
	}
	
	/**
	 * Removes all proposals for keywords that end before the given index.
	 */
	private void removeKeywordsEndingBeforeIndex(java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> proposals, int index) {
		java.util.List<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> toRemove = new java.util.ArrayList<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal>();
		for (org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal proposal : proposals) {
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedTerminal = proposal.getExpectedTerminal();
			org.emftext.language.prolog.resource.pl.IPlExpectedElement terminal = expectedTerminal.getTerminal();
			if (terminal instanceof org.emftext.language.prolog.resource.pl.mopp.PlExpectedCsString) {
				org.emftext.language.prolog.resource.pl.mopp.PlExpectedCsString csString = (org.emftext.language.prolog.resource.pl.mopp.PlExpectedCsString) terminal;
				int startExcludingHiddenTokens = expectedTerminal.getStartExcludingHiddenTokens();
				if (startExcludingHiddenTokens + csString.getValue().length() - 1 < index) {
					toRemove.add(proposal);
				}
			}
		}
		proposals.removeAll(toRemove);
	}
	
	private String findPrefix(java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> expectedElements, org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedAtCursor, String content, int cursorOffset) {
		if (cursorOffset < 0) {
			return "";
		}
		int end = 0;
		for (org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedElement : expectedElements) {
			if (expectedElement == expectedAtCursor) {
				final int start = expectedElement.getStartExcludingHiddenTokens();
				if (start >= 0  && start < Integer.MAX_VALUE) {
					end = start;
				}
				break;
			}
		}
		end = Math.min(end, cursorOffset);
		final String prefix = content.substring(end, Math.min(content.length(), cursorOffset));
		return prefix;
	}
	
	private java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> deriveProposals(java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> expectedElements, String content, org.emftext.language.prolog.resource.pl.IPlTextResource resource, int cursorOffset) {
		java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> resultSet = new java.util.LinkedHashSet<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal>();
		for (org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedElement : expectedElements) {
			resultSet.addAll(deriveProposals(expectedElement, content, resource, cursorOffset));
		}
		return resultSet;
	}
	
	private java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> deriveProposals(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedTerminal, String content, org.emftext.language.prolog.resource.pl.IPlTextResource resource, int cursorOffset) {
		org.emftext.language.prolog.resource.pl.IPlExpectedElement expectedElement = (org.emftext.language.prolog.resource.pl.IPlExpectedElement) expectedTerminal.getTerminal();
		if (expectedElement instanceof org.emftext.language.prolog.resource.pl.mopp.PlExpectedCsString) {
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedCsString csString = (org.emftext.language.prolog.resource.pl.mopp.PlExpectedCsString) expectedElement;
			return handleKeyword(expectedTerminal, csString, expectedTerminal.getPrefix());
		} else if (expectedElement instanceof org.emftext.language.prolog.resource.pl.mopp.PlExpectedBooleanTerminal) {
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedBooleanTerminal expectedBooleanTerminal = (org.emftext.language.prolog.resource.pl.mopp.PlExpectedBooleanTerminal) expectedElement;
			return handleBooleanTerminal(expectedTerminal, expectedBooleanTerminal, expectedTerminal.getPrefix());
		} else if (expectedElement instanceof org.emftext.language.prolog.resource.pl.mopp.PlExpectedEnumerationTerminal) {
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedEnumerationTerminal expectedEnumerationTerminal = (org.emftext.language.prolog.resource.pl.mopp.PlExpectedEnumerationTerminal) expectedElement;
			return handleEnumerationTerminal(expectedTerminal, expectedEnumerationTerminal, expectedTerminal.getPrefix());
		} else if (expectedElement instanceof org.emftext.language.prolog.resource.pl.mopp.PlExpectedStructuralFeature) {
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedStructuralFeature expectedFeature = (org.emftext.language.prolog.resource.pl.mopp.PlExpectedStructuralFeature) expectedElement;
			org.eclipse.emf.ecore.EStructuralFeature feature = expectedFeature.getFeature();
			org.eclipse.emf.ecore.EClassifier featureType = feature.getEType();
			org.eclipse.emf.ecore.EObject container = findCorrectContainer(expectedTerminal);
			
			if (feature instanceof org.eclipse.emf.ecore.EReference) {
				org.eclipse.emf.ecore.EReference reference = (org.eclipse.emf.ecore.EReference) feature;
				if (featureType instanceof org.eclipse.emf.ecore.EClass) {
					if (reference.isContainment()) {
						// the FOLLOW set should contain only non-containment references
						assert false;
					} else {
						return handleNCReference(expectedTerminal, container, reference, expectedTerminal.getPrefix(), expectedFeature.getTokenName());
					}
				}
			} else if (feature instanceof org.eclipse.emf.ecore.EAttribute) {
				org.eclipse.emf.ecore.EAttribute attribute = (org.eclipse.emf.ecore.EAttribute) feature;
				if (featureType instanceof org.eclipse.emf.ecore.EEnum) {
					org.eclipse.emf.ecore.EEnum enumType = (org.eclipse.emf.ecore.EEnum) featureType;
					return handleEnumAttribute(expectedTerminal, expectedFeature, enumType, expectedTerminal.getPrefix(), container);
				} else {
					// handle EAttributes (derive default value depending on the type of the
					// attribute, figure out token resolver, and call deResolve())
					return handleAttribute(expectedTerminal, expectedFeature, container, attribute, expectedTerminal.getPrefix());
				}
			} else {
				// there should be no other subclass of EStructuralFeature
				assert false;
			}
		} else {
			// there should be no other class implementing IExpectedElement
			assert false;
		}
		return java.util.Collections.emptyList();
	}
	
	private java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> handleEnumAttribute(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedTerminal, org.emftext.language.prolog.resource.pl.mopp.PlExpectedStructuralFeature expectedFeature, org.eclipse.emf.ecore.EEnum enumType, String prefix, org.eclipse.emf.ecore.EObject container) {
		java.util.Collection<org.eclipse.emf.ecore.EEnumLiteral> enumLiterals = enumType.getELiterals();
		java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> result = new java.util.LinkedHashSet<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal>();
		for (org.eclipse.emf.ecore.EEnumLiteral literal : enumLiterals) {
			String unResolvedLiteral = literal.getLiteral();
			// use token resolver to get de-resolved value of the literal
			org.emftext.language.prolog.resource.pl.IPlTokenResolverFactory tokenResolverFactory = metaInformation.getTokenResolverFactory();
			org.emftext.language.prolog.resource.pl.IPlTokenResolver tokenResolver = tokenResolverFactory.createTokenResolver(expectedFeature.getTokenName());
			String resolvedLiteral = tokenResolver.deResolve(unResolvedLiteral, expectedFeature.getFeature(), container);
			boolean matchesPrefix = matches(resolvedLiteral, prefix);
			result.add(new org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal(expectedTerminal, resolvedLiteral, prefix, matchesPrefix, expectedFeature.getFeature(), container));
		}
		return result;
	}
	
	private java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> handleNCReference(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedTerminal, org.eclipse.emf.ecore.EObject container, org.eclipse.emf.ecore.EReference reference, String prefix, String tokenName) {
		// proposals for non-containment references are derived by calling the reference
		// resolver switch in fuzzy mode.
		org.emftext.language.prolog.resource.pl.IPlReferenceResolverSwitch resolverSwitch = metaInformation.getReferenceResolverSwitch();
		org.emftext.language.prolog.resource.pl.IPlTokenResolverFactory tokenResolverFactory = metaInformation.getTokenResolverFactory();
		org.emftext.language.prolog.resource.pl.IPlReferenceResolveResult<org.eclipse.emf.ecore.EObject> result = new org.emftext.language.prolog.resource.pl.mopp.PlReferenceResolveResult<org.eclipse.emf.ecore.EObject>(true);
		resolverSwitch.resolveFuzzy(prefix, container, reference, 0, result);
		java.util.Collection<org.emftext.language.prolog.resource.pl.IPlReferenceMapping<org.eclipse.emf.ecore.EObject>> mappings = result.getMappings();
		if (mappings != null) {
			java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> resultSet = new java.util.LinkedHashSet<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal>();
			for (org.emftext.language.prolog.resource.pl.IPlReferenceMapping<org.eclipse.emf.ecore.EObject> mapping : mappings) {
				org.eclipse.swt.graphics.Image image = null;
				if (mapping instanceof org.emftext.language.prolog.resource.pl.mopp.PlElementMapping<?>) {
					org.emftext.language.prolog.resource.pl.mopp.PlElementMapping<?> elementMapping = (org.emftext.language.prolog.resource.pl.mopp.PlElementMapping<?>) mapping;
					Object target = elementMapping.getTargetElement();
					// de-resolve reference to obtain correct identifier
					org.emftext.language.prolog.resource.pl.IPlTokenResolver tokenResolver = tokenResolverFactory.createTokenResolver(tokenName);
					final String identifier = tokenResolver.deResolve(elementMapping.getIdentifier(), reference, container);
					if (target instanceof org.eclipse.emf.ecore.EObject) {
						image = getImage((org.eclipse.emf.ecore.EObject) target);
					}
					boolean matchesPrefix = matches(identifier, prefix);
					resultSet.add(new org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal(expectedTerminal, identifier, prefix, matchesPrefix, reference, container, image));
				}
			}
			return resultSet;
		}
		return java.util.Collections.emptyList();
	}
	
	private java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> handleAttribute(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedTerminal, org.emftext.language.prolog.resource.pl.mopp.PlExpectedStructuralFeature expectedFeature, org.eclipse.emf.ecore.EObject container, org.eclipse.emf.ecore.EAttribute attribute, String prefix) {
		java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> resultSet = new java.util.LinkedHashSet<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal>();
		Object[] defaultValues = attributeValueProvider.getDefaultValues(attribute);
		if (defaultValues != null) {
			for (Object defaultValue : defaultValues) {
				if (defaultValue != null) {
					org.emftext.language.prolog.resource.pl.IPlTokenResolverFactory tokenResolverFactory = metaInformation.getTokenResolverFactory();
					String tokenName = expectedFeature.getTokenName();
					if (tokenName != null) {
						org.emftext.language.prolog.resource.pl.IPlTokenResolver tokenResolver = tokenResolverFactory.createTokenResolver(tokenName);
						if (tokenResolver != null) {
							String defaultValueAsString = tokenResolver.deResolve(defaultValue, attribute, container);
							boolean matchesPrefix = matches(defaultValueAsString, prefix);
							resultSet.add(new org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal(expectedTerminal, defaultValueAsString, prefix, matchesPrefix, expectedFeature.getFeature(), container));
						}
					}
				}
			}
		}
		return resultSet;
	}
	
	/**
	 * Creates a set of completion proposals from the given keyword.
	 */
	private java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> handleKeyword(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedTerminal, org.emftext.language.prolog.resource.pl.mopp.PlExpectedCsString csString, String prefix) {
		String proposal = csString.getValue();
		boolean matchesPrefix = matches(proposal, prefix);
		return java.util.Collections.singleton(new org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal(expectedTerminal, proposal, prefix, matchesPrefix, null, null));
	}
	
	/**
	 * Creates a set of (two) completion proposals from the given boolean terminal.
	 */
	private java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> handleBooleanTerminal(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedTerminal, org.emftext.language.prolog.resource.pl.mopp.PlExpectedBooleanTerminal expectedBooleanTerminal, String prefix) {
		java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> result = new java.util.LinkedHashSet<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal>(2);
		org.emftext.language.prolog.resource.pl.grammar.PlBooleanTerminal booleanTerminal = expectedBooleanTerminal.getBooleanTerminal();
		result.addAll(handleLiteral(expectedTerminal, booleanTerminal.getAttribute(), prefix, booleanTerminal.getTrueLiteral()));
		result.addAll(handleLiteral(expectedTerminal, booleanTerminal.getAttribute(), prefix, booleanTerminal.getFalseLiteral()));
		return result;
	}
	
	/**
	 * Creates a set of completion proposals from the given enumeration terminal. For
	 * each enumeration literal one proposal is created.
	 */
	private java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> handleEnumerationTerminal(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedTerminal, org.emftext.language.prolog.resource.pl.mopp.PlExpectedEnumerationTerminal expectedEnumerationTerminal, String prefix) {
		java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> result = new java.util.LinkedHashSet<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal>(2);
		org.emftext.language.prolog.resource.pl.grammar.PlEnumerationTerminal enumerationTerminal = expectedEnumerationTerminal.getEnumerationTerminal();
		java.util.Map<String, String> literalMapping = enumerationTerminal.getLiteralMapping();
		for (String literalName : literalMapping.keySet()) {
			result.addAll(handleLiteral(expectedTerminal, enumerationTerminal.getAttribute(), prefix, literalMapping.get(literalName)));
		}
		return result;
	}
	
	private java.util.Collection<org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal> handleLiteral(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedTerminal, org.eclipse.emf.ecore.EAttribute attribute, String prefix, String literal) {
		if ("".equals(literal)) {
			return java.util.Collections.emptySet();
		}
		boolean matchesPrefix = matches(literal, prefix);
		return java.util.Collections.singleton(new org.emftext.language.prolog.resource.pl.ui.PlCompletionProposal(expectedTerminal, literal, prefix, matchesPrefix, null, null));
	}
	
	/**
	 * Calculates the prefix for each given expected element. The prefix depends on
	 * the current document content, the cursor position, and the position where the
	 * element is expected.
	 */
	private void setPrefixes(java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> expectedElements, String content, int cursorOffset) {
		if (cursorOffset < 0) {
			return;
		}
		for (org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedElement : expectedElements) {
			String prefix = findPrefix(expectedElements, expectedElement, content, cursorOffset);
			expectedElement.setPrefix(prefix);
		}
	}
	
	public org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal[] getElementsExpectedAt(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal[] allExpectedElements, int cursorOffset) {
		java.util.List<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal> expectedAtCursor = new java.util.ArrayList<org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal>();
		for (int i = 0; i < allExpectedElements.length; i++) {
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedElement = allExpectedElements[i];
			int startIncludingHidden = expectedElement.getStartIncludingHiddenTokens();
			int end = getEnd(allExpectedElements, i);
			if (cursorOffset >= startIncludingHidden && cursorOffset <= end) {
				expectedAtCursor.add(expectedElement);
			}
		}
		return expectedAtCursor.toArray(new org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal[expectedAtCursor.size()]);
	}
	
	/**
	 * Calculates the end index of the expected element at allExpectedElements[index].
	 * To determine the end, the subsequent expected elements from the array of all
	 * expected elements are used. An element is considered to end one character
	 * before the next elements starts.
	 */
	private int getEnd(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal[] allExpectedElements, int indexInList) {
		org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal elementAtIndex = allExpectedElements[indexInList];
		int startIncludingHidden = elementAtIndex.getStartIncludingHiddenTokens();
		int startExcludingHidden = elementAtIndex.getStartExcludingHiddenTokens();
		for (int i = indexInList + 1; i < allExpectedElements.length; i++) {
			org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal elementAtI = allExpectedElements[i];
			int startIncludingHiddenForI = elementAtI.getStartIncludingHiddenTokens();
			int startExcludingHiddenForI = elementAtI.getStartExcludingHiddenTokens();
			if (startIncludingHidden != startIncludingHiddenForI || startExcludingHidden != startExcludingHiddenForI) {
				return startIncludingHiddenForI - 1;
			}
		}
		return Integer.MAX_VALUE;
	}
	
	/**
	 * Checks whether the given proposed string matches the prefix. The two strings
	 * are compared ignoring the case. The prefix is also considered to match if is a
	 * camel case representation of the proposal.
	 */
	private boolean matches(String proposal, String prefix) {
		if (proposal == null || prefix == null) {
			return false;
		}
		return (proposal.toLowerCase().startsWith(prefix.toLowerCase()) || org.emftext.language.prolog.resource.pl.util.PlStringUtil.matchCamelCase(prefix, proposal) != null) && !proposal.equals(prefix);
	}
	
	private org.eclipse.swt.graphics.Image getImage(org.eclipse.emf.ecore.EObject element) {
		if (!org.eclipse.core.runtime.Platform.isRunning()) {
			return null;
		}
		org.eclipse.emf.edit.provider.ComposedAdapterFactory adapterFactory = new org.eclipse.emf.edit.provider.ComposedAdapterFactory(org.eclipse.emf.edit.provider.ComposedAdapterFactory.Descriptor.Registry.INSTANCE);
		adapterFactory.addAdapterFactory(new org.eclipse.emf.edit.provider.resource.ResourceItemProviderAdapterFactory());
		adapterFactory.addAdapterFactory(new org.eclipse.emf.ecore.provider.EcoreItemProviderAdapterFactory());
		adapterFactory.addAdapterFactory(new org.eclipse.emf.edit.provider.ReflectiveItemProviderAdapterFactory());
		org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider labelProvider = new org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider(adapterFactory);
		return labelProvider.getImage(element);
	}
	
	private org.eclipse.emf.ecore.EObject findCorrectContainer(org.emftext.language.prolog.resource.pl.mopp.PlExpectedTerminal expectedTerminal) {
		org.eclipse.emf.ecore.EObject container = expectedTerminal.getContainer();
		org.eclipse.emf.ecore.EClass ruleMetaclass = expectedTerminal.getTerminal().getRuleMetaclass();
		if (ruleMetaclass.isInstance(container)) {
			// container is correct for expectedTerminal
			return container;
		}
		// the container is wrong
		org.eclipse.emf.ecore.EObject parent = null;
		org.eclipse.emf.ecore.EObject previousParent = null;
		org.eclipse.emf.ecore.EObject correctContainer = container;
		org.emftext.language.prolog.resource.pl.mopp.PlContainedFeature currentLink = null;
		org.emftext.language.prolog.resource.pl.mopp.PlContainedFeature previousLink = null;
		org.emftext.language.prolog.resource.pl.mopp.PlContainedFeature[] containmentTrace = expectedTerminal.getContainmentTrace();
		for (int i = 0; i < containmentTrace.length; i++) {
			currentLink = containmentTrace[i];
			if (i > 0) {
				previousLink = containmentTrace[i - 1];
			}
			org.eclipse.emf.ecore.EClass containerClass = currentLink.getContainerClass();
			if (container != null && containerClass.equals(container.eClass())) {
				// we found the correct parent
				parent = container;
				break;
			} else {
				previousParent = parent;
				parent = containerClass.getEPackage().getEFactoryInstance().create(containerClass);
				if (previousParent == null) {
					// Replacing container for expectedTerminal with correctContainer
					correctContainer = parent;
				} else {
					org.emftext.language.prolog.resource.pl.util.PlEObjectUtil.setFeature(parent, previousLink.getFeature(), previousParent, false);
				}
			}
		}
		
		if (currentLink == null) {
			return correctContainer;
		}
		
		final org.eclipse.emf.ecore.EObject finalContainer = container;
		final org.eclipse.emf.ecore.EStructuralFeature finalFeature = currentLink.getFeature();
		final org.eclipse.emf.ecore.EObject finalParent = parent;
		if (parent != null) {
			expectedTerminal.setAttachmentCode(new Runnable() {
				
				public void run() {
					org.emftext.language.prolog.resource.pl.util.PlEObjectUtil.setFeature(finalContainer, finalFeature, finalParent, false);
				}
			});
		}
		return correctContainer;
	}
	
}
