<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:id="_WosmsNz1Ed2bJ_pQViWxFg"
    name="java" nsURI="http://www.emftext.org/java" nsPrefix="java">
  <eSubpackages xmi:id="_Wosmsdz1Ed2bJ_pQViWxFg" name="annotations" nsURI="http://www.emftext.org/java/annotations"
      nsPrefix="annotations">
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosmstz1Ed2bJ_pQViWxFg" name="Annotation"
        eSuperTypes="#_WosnItz1Ed2bJ_pQViWxFg #_WosnJ9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosms9z1Ed2bJ_pQViWxFg" name="AnnotationInstance"
        eSuperTypes="#_Wosmutz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosmtNz1Ed2bJ_pQViWxFg"
          name="annotation" eType="#_Wosm2tz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosmtdz1Ed2bJ_pQViWxFg"
          name="elementValuePairs" upperBound="-1" eType="#_Wosmt9z1Ed2bJ_pQViWxFg"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosmttz1Ed2bJ_pQViWxFg"
          name="elementValue" eType="#_Wosmutz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosmt9z1Ed2bJ_pQViWxFg" name="AnnotationElementValuePair"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosmuNz1Ed2bJ_pQViWxFg"
          name="key" eType="#_WosnQNz1Ed2bJ_pQViWxFg"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosmudz1Ed2bJ_pQViWxFg"
          name="value" eType="#_Wosmutz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosmutz1Ed2bJ_pQViWxFg" name="AnnotationElementValue"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosmu9z1Ed2bJ_pQViWxFg" name="AnnotationElementValueArray"
        eSuperTypes="#_Wosmutz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosmvdz1Ed2bJ_pQViWxFg"
          name="values" upperBound="-1" eType="#_Wosmutz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosmv9z1Ed2bJ_pQViWxFg" name="AnnotationMethod"
        eSuperTypes="#_Wo2Xxtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosmwNz1Ed2bJ_pQViWxFg"
          name="defaultValue" eType="#_Wosmutz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages xmi:id="_Wosmwtz1Ed2bJ_pQViWxFg" name="core" nsURI="http://www.emftext.org/java/core"
      nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X-tz1Ed2bJ_pQViWxFg" name="Package"
        eSuperTypes="#_Wosm1Nz1Ed2bJ_pQViWxFg">
      <eAnnotations xmi:id="_iNlmM9z1Ed2bJ_pQViWxFg" source="gmf.diagram"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2X_Nz1Ed2bJ_pQViWxFg"
          name="compilationUnits" upperBound="-1" eType="#_Wosmw9z1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosmw9z1Ed2bJ_pQViWxFg" name="CompilationUnit"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eAnnotations xmi:id="_uqytw9z1Ed2bJ_pQViWxFg" source="gmf.node">
        <details xmi:id="_uqytxNz1Ed2bJ_pQViWxFg" key="label" value="comments"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosmxNz1Ed2bJ_pQViWxFg"
          name="annotations" upperBound="-1" eType="#_Wosms9z1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wosmxtz1Ed2bJ_pQViWxFg"
          name="package" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosmyNz1Ed2bJ_pQViWxFg"
          name="imports" upperBound="-1" eType="#_Wosmy9z1Ed2bJ_pQViWxFg" containment="true">
        <eAnnotations xmi:id="_esffNd0PEd24uMcs4wELBA" source="gmf.compartment"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosmydz1Ed2bJ_pQViWxFg"
          name="classifiers" upperBound="-1" eType="#_WosnItz1Ed2bJ_pQViWxFg" containment="true"
          eKeys="#_Wosm1dz1Ed2bJ_pQViWxFg">
        <eAnnotations xmi:id="_Hk3jtd0MEd24uMcs4wELBA" source="gmf.compartment"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosmytz1Ed2bJ_pQViWxFg"
          name="implicitImportedClassifiers" upperBound="-1" eType="#_WosnItz1Ed2bJ_pQViWxFg"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosmy9z1Ed2bJ_pQViWxFg" name="Import"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eAnnotations xmi:id="_esffNt0PEd24uMcs4wELBA" source="gmf.node">
        <details xmi:id="_esffN90PEd24uMcs4wELBA" key="label" value="comments"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosmzNz1Ed2bJ_pQViWxFg"
          name="parts" upperBound="-1" eType="#_Wosm4tz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosmzdz1Ed2bJ_pQViWxFg" name="ClassifierImport"
        eSuperTypes="#_Wosmy9z1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosmz9z1Ed2bJ_pQViWxFg"
          name="classifiers" upperBound="-1" eType="#_WosnItz1Ed2bJ_pQViWxFg">
        <eAnnotations xmi:id="_5Ms_J91qEd2KE8FTK74D7g" source="gmf.link"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm0Nz1Ed2bJ_pQViWxFg" name="StaticImport"
        eSuperTypes="#_Wosmy9z1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm0tz1Ed2bJ_pQViWxFg"
          name="static" eType="#_Wo2Yv9z1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm09z1Ed2bJ_pQViWxFg"
          name="staticMembers" upperBound="-1" eType="#_WosnQNz1Ed2bJ_pQViWxFg">
        <eAnnotations xmi:id="_tQg39N2AEd252vaEFXhcBQ" source="gmf.link"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm1Nz1Ed2bJ_pQViWxFg" name="NamedElement"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wosm1dz1Ed2bJ_pQViWxFg"
          name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm19z1Ed2bJ_pQViWxFg" name="ReferenceableElement"
        abstract="true" eSuperTypes="#_Wosm1Nz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm2dz1Ed2bJ_pQViWxFg" name="PrimaryReference"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm2tz1Ed2bJ_pQViWxFg" name="Reference"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm29z1Ed2bJ_pQViWxFg"
          name="primary" eType="#_Wosm2dz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm3dz1Ed2bJ_pQViWxFg"
          name="arraySelectors" upperBound="-1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm3tz1Ed2bJ_pQViWxFg"
          name="next" eType="#_Wosm2tz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm4Nz1Ed2bJ_pQViWxFg" name="PackageOrClassifierReference"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm4dz1Ed2bJ_pQViWxFg"
          name="target" eType="#_Wo2ZO9z1Ed2bJ_pQViWxFg"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm4tz1Ed2bJ_pQViWxFg" name="PlainPackageOrClassifierReference"
        eSuperTypes="#_Wosm4Nz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm5Nz1Ed2bJ_pQViWxFg" name="ParameterizedPackageOrClassifierReference"
        eSuperTypes="#_Wosm4Nz1Ed2bJ_pQViWxFg #_Wosm8tz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm5tz1Ed2bJ_pQViWxFg" name="PackageOrClassifierOrMethodOrVariableReference"
        eSuperTypes="#_Wosm2dz1Ed2bJ_pQViWxFg #_Wo2YBtz1Ed2bJ_pQViWxFg #_Wosm8tz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm6Nz1Ed2bJ_pQViWxFg"
          name="target" eType="#_Wosm19z1Ed2bJ_pQViWxFg"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm6tz1Ed2bJ_pQViWxFg"
          name="arguments" upperBound="-1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm69z1Ed2bJ_pQViWxFg" name="ExplicitGenericInvocation"
        eSuperTypes="#_Wosm5tz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm7dz1Ed2bJ_pQViWxFg" name="TypeParameter"
        eSuperTypes="#_Wo2ZO9z1Ed2bJ_pQViWxFg #_Wosm19z1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm79z1Ed2bJ_pQViWxFg"
          name="extendTypes" upperBound="-1" eType="#_Wosm2tz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm8dz1Ed2bJ_pQViWxFg" name="TypeArgument"
        abstract="true" eSuperTypes="#_WosnCNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm8tz1Ed2bJ_pQViWxFg" name="TypeArgumentable"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm89z1Ed2bJ_pQViWxFg"
          name="typeArguments" upperBound="-1" eType="#_Wosm8dz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm9dz1Ed2bJ_pQViWxFg" name="QualifiedTypeArgument"
        eSuperTypes="#_Wosm8dz1Ed2bJ_pQViWxFg #_Wo2ZP9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm99z1Ed2bJ_pQViWxFg" name="ExtendsTypeArgument"
        eSuperTypes="#_Wosm8dz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm-dz1Ed2bJ_pQViWxFg"
          name="extendTypes" upperBound="-1" eType="#_Wosm2tz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm-9z1Ed2bJ_pQViWxFg" name="SuperTypeArgument"
        eSuperTypes="#_Wosm8dz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wosm_dz1Ed2bJ_pQViWxFg"
          name="superType" eType="#_Wosm2tz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wosm_9z1Ed2bJ_pQViWxFg" name="UnknownTypeArgument"
        eSuperTypes="#_Wosm8dz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnAdz1Ed2bJ_pQViWxFg" name="TypeParametrizable"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnAtz1Ed2bJ_pQViWxFg"
          name="typeParameters" upperBound="-1" eType="#_Wosm7dz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnBNz1Ed2bJ_pQViWxFg" name="Parametrizable"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnBdz1Ed2bJ_pQViWxFg"
          name="parameters" upperBound="-1" eType="#_Wo2X19z1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnBtz1Ed2bJ_pQViWxFg" name="Initializable"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnB9z1Ed2bJ_pQViWxFg"
          name="initialValue" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnCNz1Ed2bJ_pQViWxFg" name="ArrayTypable"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnCdz1Ed2bJ_pQViWxFg"
          name="arrayDimensions" upperBound="-1" eType="#_Wo2X6dz1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnCtz1Ed2bJ_pQViWxFg" name="Instantiation"
        abstract="true" eSuperTypes="#_Wo2ZP9z1Ed2bJ_pQViWxFg #_Wo2YBtz1Ed2bJ_pQViWxFg #_Wosm8tz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnDNz1Ed2bJ_pQViWxFg"
          name="arguments" upperBound="-1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnDdz1Ed2bJ_pQViWxFg" name="NewConstructorCall"
        eSuperTypes="#_WosnCtz1Ed2bJ_pQViWxFg #_Wosm2dz1Ed2bJ_pQViWxFg #_WosnJ9z1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnENz1Ed2bJ_pQViWxFg"
          name="classTypeArguments" upperBound="-1" eType="#_Wosm8dz1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnEtz1Ed2bJ_pQViWxFg" name="ExplicitConstructorCall"
        eSuperTypes="#_WosnCtz1Ed2bJ_pQViWxFg #_Wosm2dz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnFdz1Ed2bJ_pQViWxFg"
          name="callTarget" eType="#_Wo2X7tz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnFtz1Ed2bJ_pQViWxFg" name="ArrayInstantiationBySize"
        eSuperTypes="#_Wo2YDNz1Ed2bJ_pQViWxFg #_Wo2ZP9z1Ed2bJ_pQViWxFg #_WosnCNz1Ed2bJ_pQViWxFg #_Wosm2dz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnGdz1Ed2bJ_pQViWxFg"
          name="sizes" upperBound="-1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnGtz1Ed2bJ_pQViWxFg" name="ArrayInstantiationByValues"
        eSuperTypes="#_Wo2YDNz1Ed2bJ_pQViWxFg #_Wo2ZP9z1Ed2bJ_pQViWxFg #_WosnCNz1Ed2bJ_pQViWxFg #_Wosm2dz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnHdz1Ed2bJ_pQViWxFg"
          name="arrayInitializer" eType="#_WosnHtz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnHtz1Ed2bJ_pQViWxFg" name="ArrayInitializer"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnH9z1Ed2bJ_pQViWxFg"
          name="arrayInitializers" upperBound="-1" eType="#_WosnHtz1Ed2bJ_pQViWxFg"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnIdz1Ed2bJ_pQViWxFg"
          name="initialValues" upperBound="-1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnItz1Ed2bJ_pQViWxFg" name="Classifier"
        abstract="true" eSuperTypes="#_Wo2ZO9z1Ed2bJ_pQViWxFg #_WosnAdz1Ed2bJ_pQViWxFg #_WosnQNz1Ed2bJ_pQViWxFg #_Wosm1Nz1Ed2bJ_pQViWxFg #_Wo2YzNz1Ed2bJ_pQViWxFg #_Wosm19z1Ed2bJ_pQViWxFg">
      <eAnnotations xmi:id="_PYWuI90MEd24uMcs4wELBA" source="gmf.node">
        <details xmi:id="_PYWuJN0MEd24uMcs4wELBA" key="label" value="name"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnJtz1Ed2bJ_pQViWxFg"
          name="modifiers" upperBound="-1" eType="#_Wo2Ys9z1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnJ9z1Ed2bJ_pQViWxFg" name="MemberContainer"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnKNz1Ed2bJ_pQViWxFg"
          name="members" upperBound="-1" eType="#_WosnQNz1Ed2bJ_pQViWxFg" containment="true"
          eKeys="#_Wosm1dz1Ed2bJ_pQViWxFg">
        <eAnnotations xmi:id="_PKY_v92FEd2aWNLZl1Ap0g" source="gmf.compartment"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnKdz1Ed2bJ_pQViWxFg" name="Implementor"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnKtz1Ed2bJ_pQViWxFg"
          name="implements" upperBound="-1" eType="#_Wosm9dz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnLNz1Ed2bJ_pQViWxFg" name="Class"
        eSuperTypes="#_WosnItz1Ed2bJ_pQViWxFg #_WosnJ9z1Ed2bJ_pQViWxFg #_WosnKdz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnMNz1Ed2bJ_pQViWxFg"
          name="extends" eType="#_Wosm9dz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnMtz1Ed2bJ_pQViWxFg" name="Interface"
        eSuperTypes="#_WosnItz1Ed2bJ_pQViWxFg #_WosnJ9z1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnNdz1Ed2bJ_pQViWxFg"
          name="extends" upperBound="-1" eType="#_Wosm9dz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnN9z1Ed2bJ_pQViWxFg" name="Enumeration"
        eSuperTypes="#_WosnItz1Ed2bJ_pQViWxFg #_WosnJ9z1Ed2bJ_pQViWxFg #_WosnKdz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnO9z1Ed2bJ_pQViWxFg"
          name="constants" upperBound="-1" eType="#_WosnPNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnPNz1Ed2bJ_pQViWxFg" name="EnumConstant"
        eSuperTypes="#_Wosm1Nz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnPtz1Ed2bJ_pQViWxFg"
          name="arguments" upperBound="-1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_WosnP9z1Ed2bJ_pQViWxFg"
          name="members" upperBound="-1" eType="#_WosnQNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnQNz1Ed2bJ_pQViWxFg" name="Member"
        abstract="true" eSuperTypes="#_Wosm1Nz1Ed2bJ_pQViWxFg">
      <eAnnotations xmi:id="_y_E9Td2AEd252vaEFXhcBQ" source="gmf.node">
        <details xmi:id="_y_E9Tt2AEd252vaEFXhcBQ" key="label" value="name"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_WosnQtz1Ed2bJ_pQViWxFg" name="ExceptionThrower"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2XsNz1Ed2bJ_pQViWxFg"
          name="exceptions" upperBound="-1" eType="#_Wo2ZQ9z1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Xsdz1Ed2bJ_pQViWxFg" name="Constructor"
        eSuperTypes="#_WosnQNz1Ed2bJ_pQViWxFg #_WosnBNz1Ed2bJ_pQViWxFg #_WosnQtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Xtdz1Ed2bJ_pQViWxFg"
          name="modifiers" upperBound="-1" eType="#_Wo2Ys9z1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Xttz1Ed2bJ_pQViWxFg"
          name="body" lowerBound="1" eType="#_Wo2X5dz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Xt9z1Ed2bJ_pQViWxFg"
          name="typeParameters" upperBound="-1" eType="#_Wosm7dz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Xudz1Ed2bJ_pQViWxFg"
          name="annotations" upperBound="-1" eType="#_Wosms9z1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Xu9z1Ed2bJ_pQViWxFg" name="Field"
        eSuperTypes="#_WosnQNz1Ed2bJ_pQViWxFg #_WosnBtz1Ed2bJ_pQViWxFg #_Wo2X0dz1Ed2bJ_pQViWxFg #_Wosm19z1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Xv9z1Ed2bJ_pQViWxFg"
          name="additionalFields" upperBound="-1" eType="#_Wo2X4dz1Ed2bJ_pQViWxFg"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2XwNz1Ed2bJ_pQViWxFg"
          name="annotations" upperBound="-1" eType="#_Wosms9z1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Xwtz1Ed2bJ_pQViWxFg" name="AdditionalField"
        eSuperTypes="#_Wosm19z1Ed2bJ_pQViWxFg #_WosnCNz1Ed2bJ_pQViWxFg #_WosnBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Xxtz1Ed2bJ_pQViWxFg" name="Method"
        eSuperTypes="#_Wo2ZP9z1Ed2bJ_pQViWxFg #_WosnCNz1Ed2bJ_pQViWxFg #_WosnAdz1Ed2bJ_pQViWxFg #_WosnBNz1Ed2bJ_pQViWxFg #_WosnQNz1Ed2bJ_pQViWxFg #_Wosm19z1Ed2bJ_pQViWxFg #_WosnQtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Xzdz1Ed2bJ_pQViWxFg"
          name="modifiers" upperBound="-1" eType="#_Wo2Ys9z1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Xztz1Ed2bJ_pQViWxFg"
          name="body" eType="#_Wo2X5dz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Xz9z1Ed2bJ_pQViWxFg"
          name="annotations" upperBound="-1" eType="#_Wosms9z1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X0dz1Ed2bJ_pQViWxFg" name="Variable"
        abstract="true" eSuperTypes="#_Wosm1Nz1Ed2bJ_pQViWxFg #_Wo2ZP9z1Ed2bJ_pQViWxFg #_WosnCNz1Ed2bJ_pQViWxFg #_Wosm19z1Ed2bJ_pQViWxFg #_Wosm8tz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2X1tz1Ed2bJ_pQViWxFg"
          name="modifiers" upperBound="-1" eType="#_Wo2Ys9z1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X19z1Ed2bJ_pQViWxFg" name="Parameter"
        abstract="true" eSuperTypes="#_Wo2X0dz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X2dz1Ed2bJ_pQViWxFg" name="OrdinaryParameter"
        eSuperTypes="#_Wo2X19z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X29z1Ed2bJ_pQViWxFg" name="VariableLengthParameter"
        eSuperTypes="#_Wo2X19z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X3dz1Ed2bJ_pQViWxFg" name="LocalVariable"
        eSuperTypes="#_Wo2X0dz1Ed2bJ_pQViWxFg #_WosnBtz1Ed2bJ_pQViWxFg #_Wo2Y9tz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2X4Nz1Ed2bJ_pQViWxFg"
          name="additionalLocalVariables" upperBound="-1" eType="#_Wo2X4dz1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X4dz1Ed2bJ_pQViWxFg" name="AdditionalLocalVariable"
        eSuperTypes="#_Wosm19z1Ed2bJ_pQViWxFg #_WosnCNz1Ed2bJ_pQViWxFg #_WosnBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X5dz1Ed2bJ_pQViWxFg" name="Block"
        eSuperTypes="#_WosnQNz1Ed2bJ_pQViWxFg #_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2X59z1Ed2bJ_pQViWxFg"
          name="modifiers" upperBound="-1" eType="#_Wo2Ys9z1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2X6Nz1Ed2bJ_pQViWxFg"
          name="statements" upperBound="-1" eType="#_Wo2YzNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X6dz1Ed2bJ_pQViWxFg" name="ArrayDimension"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X6tz1Ed2bJ_pQViWxFg" name="Primary"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2X69z1Ed2bJ_pQViWxFg"
          name="reference" eType="#_Wosm2tz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2X7dz1Ed2bJ_pQViWxFg"
          name="literal" eType="#_Wo2YsNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X7tz1Ed2bJ_pQViWxFg" name="SelfReference"
        eSuperTypes="#_Wosm2dz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X8Nz1Ed2bJ_pQViWxFg" name="This"
        eSuperTypes="#_Wo2X7tz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X8tz1Ed2bJ_pQViWxFg" name="Super"
        eSuperTypes="#_Wo2X7tz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X9Nz1Ed2bJ_pQViWxFg" name="ClassLiteral"
        eSuperTypes="#_Wosm2dz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X9tz1Ed2bJ_pQViWxFg" name="PackageDescriptor"
        eSuperTypes="#_WosnItz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2X-Nz1Ed2bJ_pQViWxFg"
          name="parent" eType="#_Wo2X9tz1Ed2bJ_pQViWxFg"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages xmi:id="_Wo2X_tz1Ed2bJ_pQViWxFg" name="comments" nsURI="http://www.emftext.org/java/comments"
      nsPrefix="comments">
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2X_9z1Ed2bJ_pQViWxFg" name="Comment"
        abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2YANz1Ed2bJ_pQViWxFg"
          name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YAtz1Ed2bJ_pQViWxFg" name="SingleLineComment"
        eSuperTypes="#_Wo2X_9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YBNz1Ed2bJ_pQViWxFg" name="MultiLineComment"
        eSuperTypes="#_Wo2X_9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YBtz1Ed2bJ_pQViWxFg" name="Commentable"
        abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2YB9z1Ed2bJ_pQViWxFg"
          name="comments" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2YCdz1Ed2bJ_pQViWxFg"
          name="whitespaces" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages xmi:id="_Wo2YC9z1Ed2bJ_pQViWxFg" name="expressions" nsURI="http://www.emftext.org/java/expressions"
      nsPrefix="expressions">
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YDNz1Ed2bJ_pQViWxFg" name="Expression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YDtz1Ed2bJ_pQViWxFg"
          name="conditionalExpression" eType="#_Wo2YIdz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YD9z1Ed2bJ_pQViWxFg"
          name="expression" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YEdz1Ed2bJ_pQViWxFg"
          name="assignmentOperator" eType="#_Wo2YcNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YEtz1Ed2bJ_pQViWxFg" name="ParExpression"
        eSuperTypes="#_Wosm2dz1Ed2bJ_pQViWxFg #_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YFdz1Ed2bJ_pQViWxFg"
          name="expression" lowerBound="1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YF9z1Ed2bJ_pQViWxFg" name="ExpressionList"
        eSuperTypes="#_Wo2Y9tz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YGNz1Ed2bJ_pQViWxFg"
          name="expressions" upperBound="-1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YGtz1Ed2bJ_pQViWxFg" name="ConditionalAndExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YHNz1Ed2bJ_pQViWxFg"
          name="inclusiveOrExpression" upperBound="-1" eType="#_Wo2YJ9z1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YHdz1Ed2bJ_pQViWxFg" name="ConditionalOrExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YH9z1Ed2bJ_pQViWxFg"
          name="conditionalAndExpression" upperBound="-1" eType="#_Wo2YGtz1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YIdz1Ed2bJ_pQViWxFg" name="ConditionalExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YI9z1Ed2bJ_pQViWxFg"
          name="conditionalOrExpression" eType="#_Wo2YHdz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YJdz1Ed2bJ_pQViWxFg"
          name="expression" upperBound="-1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YJ9z1Ed2bJ_pQViWxFg" name="InclusiveOrExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YKdz1Ed2bJ_pQViWxFg"
          name="exclusiveOrExpression" upperBound="-1" eType="#_Wo2YKtz1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YKtz1Ed2bJ_pQViWxFg" name="ExclusiveOrExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YLNz1Ed2bJ_pQViWxFg"
          name="andExpression" upperBound="-1" eType="#_Wo2YLdz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YLdz1Ed2bJ_pQViWxFg" name="AndExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YL9z1Ed2bJ_pQViWxFg"
          name="equalityExpression" upperBound="-1" eType="#_Wo2YMNz1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YMNz1Ed2bJ_pQViWxFg" name="EqualityExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YMtz1Ed2bJ_pQViWxFg"
          name="instanceOfExpression" upperBound="-1" eType="#_Wo2YNdz1Ed2bJ_pQViWxFg"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YM9z1Ed2bJ_pQViWxFg"
          name="equal" upperBound="-1" eType="#_Wo2Yb9z1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YNNz1Ed2bJ_pQViWxFg"
          name="notEqual" upperBound="-1" eType="#_Wo2Yi9z1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YNdz1Ed2bJ_pQViWxFg" name="InstanceOfExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg #_WosnCNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YONz1Ed2bJ_pQViWxFg"
          name="relationExpression" eType="#_Wo2YOtz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YOdz1Ed2bJ_pQViWxFg"
          name="type" eType="#_Wo2ZPdz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YOtz1Ed2bJ_pQViWxFg" name="RelationExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YPNz1Ed2bJ_pQViWxFg"
          name="shiftExpression" upperBound="-1" eType="#_Wo2YPtz1Ed2bJ_pQViWxFg"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YPdz1Ed2bJ_pQViWxFg"
          name="relationOperator" upperBound="-1" eType="#_Wo2YX9z1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YPtz1Ed2bJ_pQViWxFg" name="ShiftExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YQNz1Ed2bJ_pQViWxFg"
          name="additiveExpression" upperBound="-1" eType="#_Wo2YQtz1Ed2bJ_pQViWxFg"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YQdz1Ed2bJ_pQViWxFg"
          name="shiftOperator" upperBound="-1" eType="#_Wo2YaNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YQtz1Ed2bJ_pQViWxFg" name="AdditiveExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YRNz1Ed2bJ_pQViWxFg"
          name="multiplicativeExpression" upperBound="-1" eType="#_Wo2YRtz1Ed2bJ_pQViWxFg"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YRdz1Ed2bJ_pQViWxFg"
          name="additiveOperator" upperBound="-1" eType="#_Wo2Yjtz1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YRtz1Ed2bJ_pQViWxFg" name="MultiplicativeExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YSNz1Ed2bJ_pQViWxFg"
          name="unaryExpression" upperBound="-1" eType="#_Wo2YStz1Ed2bJ_pQViWxFg"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YSdz1Ed2bJ_pQViWxFg"
          name="multiplicativeOperator" upperBound="-1" eType="#_Wo2Yktz1Ed2bJ_pQViWxFg"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YStz1Ed2bJ_pQViWxFg" name="UnaryExpression"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YTNz1Ed2bJ_pQViWxFg"
          name="additiveOperator" eType="#_Wo2Yjtz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YTdz1Ed2bJ_pQViWxFg"
          name="plusplus" eType="#_Wo2Yltz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YTtz1Ed2bJ_pQViWxFg"
          name="minusminus" eType="#_Wo2YmNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YT9z1Ed2bJ_pQViWxFg"
          name="unaryExpressionNotPlusMinus" eType="#_Wo2YUNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YUNz1Ed2bJ_pQViWxFg" name="UnaryExpressionNotPlusMinus"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YUtz1Ed2bJ_pQViWxFg"
          name="primary" eType="#_Wo2X6tz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YVNz1Ed2bJ_pQViWxFg"
          name="castExpression" eType="#_Wo2YWdz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YVdz1Ed2bJ_pQViWxFg"
          name="complement" eType="#_Wo2Ymtz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YVtz1Ed2bJ_pQViWxFg"
          name="negate" eType="#_Wo2YnNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YV9z1Ed2bJ_pQViWxFg"
          name="plusplus" eType="#_Wo2Yltz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YWNz1Ed2bJ_pQViWxFg"
          name="minusminus" eType="#_Wo2YmNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YWdz1Ed2bJ_pQViWxFg" name="CastExpression"
        eSuperTypes="#_WosnCNz1Ed2bJ_pQViWxFg #_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YXNz1Ed2bJ_pQViWxFg"
          name="typeReference" eType="#_Wo2ZPdz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2YXdz1Ed2bJ_pQViWxFg"
          name="expression" eType="#_Wo2YStz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YX9z1Ed2bJ_pQViWxFg" name="RelationOperator"
        abstract="true" eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YYNz1Ed2bJ_pQViWxFg" name="LessThan"
        eSuperTypes="#_Wo2YX9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YYtz1Ed2bJ_pQViWxFg" name="LessThanOrEqual"
        eSuperTypes="#_Wo2YX9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YZNz1Ed2bJ_pQViWxFg" name="GreaterThan"
        eSuperTypes="#_Wo2YX9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YZtz1Ed2bJ_pQViWxFg" name="GreaterThanOrEqual"
        eSuperTypes="#_Wo2YX9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YaNz1Ed2bJ_pQViWxFg" name="ShiftOperator"
        abstract="true" eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yadz1Ed2bJ_pQViWxFg" name="LeftShift"
        eSuperTypes="#_Wo2YaNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Ya9z1Ed2bJ_pQViWxFg" name="RightShift"
        eSuperTypes="#_Wo2YaNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Ybdz1Ed2bJ_pQViWxFg" name="UnsignedRightShift"
        eSuperTypes="#_Wo2YaNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yb9z1Ed2bJ_pQViWxFg" name="Equal"
        eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YcNz1Ed2bJ_pQViWxFg" name="AssignmentOperator"
        abstract="true" eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2Ycdz1Ed2bJ_pQViWxFg"
          name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yc9z1Ed2bJ_pQViWxFg" name="Assignment"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yddz1Ed2bJ_pQViWxFg" name="CompoundAssignmentMinus"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yd9z1Ed2bJ_pQViWxFg" name="CompoundAssignmentPlus"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yedz1Ed2bJ_pQViWxFg" name="CompoundAssignmentMultiplication"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Ye9z1Ed2bJ_pQViWxFg" name="CompoundAssignmentDivision"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yfdz1Ed2bJ_pQViWxFg" name="CompoundAssignmentModulo"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yf9z1Ed2bJ_pQViWxFg" name="CompoundAssignmentAnd"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Ygdz1Ed2bJ_pQViWxFg" name="CompoundAssignmentOr"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yg9z1Ed2bJ_pQViWxFg" name="CompoundAssignmentExclusiveOr"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yhdz1Ed2bJ_pQViWxFg" name="CompoundAssignmentLeftShift"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yh9z1Ed2bJ_pQViWxFg" name="CompoundAssignmentRightShift"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yidz1Ed2bJ_pQViWxFg" name="CompoundAssignmentUnsignedRightShift"
        eSuperTypes="#_Wo2YcNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yi9z1Ed2bJ_pQViWxFg" name="NotEqual"
        eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YjNz1Ed2bJ_pQViWxFg" name="Operator"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yjtz1Ed2bJ_pQViWxFg" name="AdditiveOperator"
        eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2YkNz1Ed2bJ_pQViWxFg"
          name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yktz1Ed2bJ_pQViWxFg" name="MultiplicativeOperator"
        eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2YlNz1Ed2bJ_pQViWxFg"
          name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yltz1Ed2bJ_pQViWxFg" name="PlusPlus"
        eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YmNz1Ed2bJ_pQViWxFg" name="MinusMinus"
        eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Ymtz1Ed2bJ_pQViWxFg" name="Complement"
        eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YnNz1Ed2bJ_pQViWxFg" name="Negate"
        eSuperTypes="#_Wo2YjNz1Ed2bJ_pQViWxFg"/>
  </eSubpackages>
  <eSubpackages xmi:id="_Wo2Yntz1Ed2bJ_pQViWxFg" name="literals" nsURI="http://www.emftext.org/java/literals"
      nsPrefix="literals">
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yn9z1Ed2bJ_pQViWxFg" name="IntegerLiteral"
        eSuperTypes="#_Wo2YsNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2YoNz1Ed2bJ_pQViWxFg"
          name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yotz1Ed2bJ_pQViWxFg" name="FloatingPointLiteral"
        eSuperTypes="#_Wo2YsNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2Yo9z1Ed2bJ_pQViWxFg"
          name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Ypdz1Ed2bJ_pQViWxFg" name="CharacterLiteral"
        eSuperTypes="#_Wo2YsNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2Yptz1Ed2bJ_pQViWxFg"
          name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YqNz1Ed2bJ_pQViWxFg" name="StringLiteral"
        eSuperTypes="#_Wo2YsNz1Ed2bJ_pQViWxFg #_Wosm2dz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2Yqtz1Ed2bJ_pQViWxFg"
          name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YrNz1Ed2bJ_pQViWxFg" name="BooleanLiteral"
        eSuperTypes="#_Wo2YsNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2Yrdz1Ed2bJ_pQViWxFg"
          name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yr9z1Ed2bJ_pQViWxFg" name="NullLiteral"
        eSuperTypes="#_Wo2YsNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YsNz1Ed2bJ_pQViWxFg" name="Literal"
        abstract="true" eSuperTypes="#_Wosmutz1Ed2bJ_pQViWxFg"/>
  </eSubpackages>
  <eSubpackages xmi:id="_Wo2Ystz1Ed2bJ_pQViWxFg" name="modifiers" nsURI="http://www.emftext.org/java/modifiers"
      nsPrefix="modifiers">
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Ys9z1Ed2bJ_pQViWxFg" name="Modifier"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Ytdz1Ed2bJ_pQViWxFg" name="Public"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yt9z1Ed2bJ_pQViWxFg" name="Abstract"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yudz1Ed2bJ_pQViWxFg" name="Protected"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yu9z1Ed2bJ_pQViWxFg" name="Private"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yvdz1Ed2bJ_pQViWxFg" name="Final"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yv9z1Ed2bJ_pQViWxFg" name="Static"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Ywdz1Ed2bJ_pQViWxFg" name="Native"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yw9z1Ed2bJ_pQViWxFg" name="Synchronized"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yxdz1Ed2bJ_pQViWxFg" name="Transient"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yx9z1Ed2bJ_pQViWxFg" name="Volatile"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yydz1Ed2bJ_pQViWxFg" name="Strictfp"
        eSuperTypes="#_Wo2Ys9z1Ed2bJ_pQViWxFg"/>
  </eSubpackages>
  <eSubpackages xmi:id="_Wo2Yy9z1Ed2bJ_pQViWxFg" name="statements" nsURI="http://www.emftext.org/java/statements"
      nsPrefix="statements">
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2YzNz1Ed2bJ_pQViWxFg" name="Statement"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Yztz1Ed2bJ_pQViWxFg" name="Assert"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y0Nz1Ed2bJ_pQViWxFg"
          name="expression1" lowerBound="1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y0tz1Ed2bJ_pQViWxFg"
          name="expression2" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Y1Nz1Ed2bJ_pQViWxFg" name="Condition"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y1tz1Ed2bJ_pQViWxFg"
          name="expression" lowerBound="1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y2Nz1Ed2bJ_pQViWxFg"
          name="ifStatement" lowerBound="1" eType="#_Wo2YzNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y2tz1Ed2bJ_pQViWxFg"
          name="elseStatement" eType="#_Wo2YzNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Y3Nz1Ed2bJ_pQViWxFg" name="Switch"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y3tz1Ed2bJ_pQViWxFg"
          name="cases" upperBound="-1" eType="#_Wo2Y4tz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y4Nz1Ed2bJ_pQViWxFg"
          name="variable" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Y4tz1Ed2bJ_pQViWxFg" name="SwitchCase"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y5Nz1Ed2bJ_pQViWxFg"
          name="condition" lowerBound="1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y5tz1Ed2bJ_pQViWxFg"
          name="body" upperBound="-1" eType="#_Wo2YzNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y6Nz1Ed2bJ_pQViWxFg"
          name="break" eType="#_Wo2ZI9z1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Y6dz1Ed2bJ_pQViWxFg" name="NormalSwitchCase"
        eSuperTypes="#_Wo2Y4tz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Y69z1Ed2bJ_pQViWxFg" name="DefaultSwitchCase"
        eSuperTypes="#_Wo2Y4tz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Y7dz1Ed2bJ_pQViWxFg" name="ForLoop"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y79z1Ed2bJ_pQViWxFg"
          name="init" eType="#_Wo2Y9tz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y8Nz1Ed2bJ_pQViWxFg"
          name="condition" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y8tz1Ed2bJ_pQViWxFg"
          name="updates" upperBound="-1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y9Nz1Ed2bJ_pQViWxFg"
          name="body" lowerBound="1" eType="#_Wo2YzNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Y9tz1Ed2bJ_pQViWxFg" name="ForLoopInitializer"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2Y-Nz1Ed2bJ_pQViWxFg" name="ForEachLoop"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y-tz1Ed2bJ_pQViWxFg"
          name="next" eType="#_Wo2X2dz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y_Nz1Ed2bJ_pQViWxFg"
          name="collection" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2Y_tz1Ed2bJ_pQViWxFg"
          name="body" lowerBound="1" eType="#_Wo2YzNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZANz1Ed2bJ_pQViWxFg" name="WhileLoop"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZAtz1Ed2bJ_pQViWxFg"
          name="condition" lowerBound="1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZBNz1Ed2bJ_pQViWxFg"
          name="body" lowerBound="1" eType="#_Wo2YzNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZBtz1Ed2bJ_pQViWxFg" name="DoWhileLoop"
        eSuperTypes="#_Wo2ZANz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZCNz1Ed2bJ_pQViWxFg" name="TryBlock"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZCtz1Ed2bJ_pQViWxFg"
          name="tryBlock" lowerBound="1" eType="#_Wo2X5dz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZDNz1Ed2bJ_pQViWxFg"
          name="finallyBlock" eType="#_Wo2X5dz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZDtz1Ed2bJ_pQViWxFg"
          name="catches" upperBound="-1" eType="#_Wo2ZD9z1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZD9z1Ed2bJ_pQViWxFg" name="CatchClause"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZEdz1Ed2bJ_pQViWxFg"
          name="parameter" lowerBound="1" eType="#_Wo2X2dz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZE9z1Ed2bJ_pQViWxFg"
          name="catchBlock" lowerBound="1" eType="#_Wo2X5dz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZFdz1Ed2bJ_pQViWxFg" name="SynchronizedBlock"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZF9z1Ed2bJ_pQViWxFg"
          name="lockExpression" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZGdz1Ed2bJ_pQViWxFg"
          name="body" lowerBound="1" eType="#_Wo2X5dz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZG9z1Ed2bJ_pQViWxFg" name="Return"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZHdz1Ed2bJ_pQViWxFg"
          name="expression" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZH9z1Ed2bJ_pQViWxFg" name="Throw"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZIdz1Ed2bJ_pQViWxFg"
          name="expression" lowerBound="1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZI9z1Ed2bJ_pQViWxFg" name="Break"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2ZJdz1Ed2bJ_pQViWxFg"
          name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZJ9z1Ed2bJ_pQViWxFg" name="Continue"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Wo2ZKdz1Ed2bJ_pQViWxFg"
          name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZK9z1Ed2bJ_pQViWxFg" name="EmptyStatement"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZLdz1Ed2bJ_pQViWxFg" name="JumpLabel"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg #_Wosm1Nz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZMNz1Ed2bJ_pQViWxFg"
          name="statement" lowerBound="1" eType="#_Wo2YzNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZMtz1Ed2bJ_pQViWxFg" name="ExpressionStatement"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZNNz1Ed2bJ_pQViWxFg"
          name="expression" lowerBound="1" eType="#_Wo2YDNz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZNtz1Ed2bJ_pQViWxFg" name="LocalVariableStatement"
        eSuperTypes="#_Wo2YzNz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZONz1Ed2bJ_pQViWxFg"
          name="variable" eType="#_Wo2X3dz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages xmi:id="_Wo2ZOtz1Ed2bJ_pQViWxFg" name="types" nsURI="http://www.emftext.org/java/types"
      nsPrefix="types">
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZO9z1Ed2bJ_pQViWxFg" name="Type"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZPdz1Ed2bJ_pQViWxFg" name="TypeReference"
        abstract="true" eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZP9z1Ed2bJ_pQViWxFg" name="TypedElement"
        eSuperTypes="#_Wo2YBtz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZQdz1Ed2bJ_pQViWxFg"
          name="type" eType="#_Wo2ZPdz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZQ9z1Ed2bJ_pQViWxFg" name="TypeReferenceSequence"
        eSuperTypes="#_Wo2ZPdz1Ed2bJ_pQViWxFg">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Wo2ZRdz1Ed2bJ_pQViWxFg"
          name="parts" upperBound="-1" eType="#_Wosm5Nz1Ed2bJ_pQViWxFg" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZR9z1Ed2bJ_pQViWxFg" name="PrimitiveType"
        abstract="true" eSuperTypes="#_Wosm2dz1Ed2bJ_pQViWxFg #_Wo2ZPdz1Ed2bJ_pQViWxFg #_Wo2ZO9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZS9z1Ed2bJ_pQViWxFg" name="Boolean"
        eSuperTypes="#_Wo2ZR9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZTdz1Ed2bJ_pQViWxFg" name="Char"
        eSuperTypes="#_Wo2ZR9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZT9z1Ed2bJ_pQViWxFg" name="Byte"
        eSuperTypes="#_Wo2ZR9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZUdz1Ed2bJ_pQViWxFg" name="Short"
        eSuperTypes="#_Wo2ZR9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZU9z1Ed2bJ_pQViWxFg" name="Int"
        eSuperTypes="#_Wo2ZR9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZVdz1Ed2bJ_pQViWxFg" name="Long"
        eSuperTypes="#_Wo2ZR9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZV9z1Ed2bJ_pQViWxFg" name="Float"
        eSuperTypes="#_Wo2ZR9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZWdz1Ed2bJ_pQViWxFg" name="Double"
        eSuperTypes="#_Wo2ZR9z1Ed2bJ_pQViWxFg"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Wo2ZW9z1Ed2bJ_pQViWxFg" name="VoidLiteral"
        eSuperTypes="#_Wo2ZR9z1Ed2bJ_pQViWxFg"/>
  </eSubpackages>
</ecore:EPackage>
