<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="java"
    nsURI="http://www.emftext.org/java" nsPrefix="java">
  <eSubpackages name="annotations" nsURI="http://www.emftext.org/java/annotations"
      nsPrefix="annotations">
    <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//core/Classifier #//core/MemberContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationInstance" eSuperTypes="#//annotations/AnnotationElementValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" eType="#//core/Reference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementValuePairs" upperBound="-1"
          eType="#//annotations/AnnotationElementValuePair" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementValue" eType="#//annotations/AnnotationElementValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationElementValuePair">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//core/Member"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//annotations/AnnotationElementValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationElementValue" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationElementValueArray" eSuperTypes="#//annotations/AnnotationElementValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          eType="#//annotations/AnnotationElementValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMethod" eSuperTypes="#//core/Method">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//annotations/AnnotationElementValue"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="core" nsURI="http://www.emftext.org/java/core" nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#//annotations/AnnotationInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
          eType="#//core/Import" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifiers" upperBound="-1"
          eType="#//core/Classifier" containment="true" eKeys="#//core/NamedElement/name"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implicitImportedClassifiers"
          upperBound="-1" eType="#//core/Classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Import" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
          eType="#//core/PlainPackageOrClassifierReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassifierImport" eSuperTypes="#//core/Import">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifiers" upperBound="-1"
          eType="#//core/Classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaticImport" eSuperTypes="#//core/Import">
      <eStructuralFeatures xsi:type="ecore:EReference" name="static" eType="#//modifiers/Static"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="staticMembers" upperBound="-1"
          eType="#//core/Member"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceableElement" abstract="true"
        eSuperTypes="#//core/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimaryReference" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Reference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="primary" eType="#//core/PrimaryReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arraySelectors" upperBound="-1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//core/Reference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PackageOrClassifierReference" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//types/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PlainPackageOrClassifierReference"
        eSuperTypes="#//core/PackageOrClassifierReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterizedPackageOrClassifierReference"
        eSuperTypes="#//core/PackageOrClassifierReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
          eType="#//core/TypeArgument" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PackageOrClassifierOrMethodOrVariableReference"
        eSuperTypes="#//core/PrimaryReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//core/ReferenceableElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
          eType="#//core/TypeArgument" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExplicitGenericInvocation" eSuperTypes="#//core/PackageOrClassifierOrMethodOrVariableReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeParameter" eSuperTypes="#//types/Type #//core/ReferenceableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extendTypes" upperBound="-1"
          eType="#//core/Reference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeArgument" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="QualifiedTypeArgument" eSuperTypes="#//core/TypeArgument #//types/TypedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExtendsTypeArgument" eSuperTypes="#//core/TypeArgument">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extendTypes" upperBound="-1"
          eType="#//core/Reference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuperTypeArgument" eSuperTypes="#//core/TypeArgument">
      <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//core/Reference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnknownTypeArgument" eSuperTypes="#//core/TypeArgument"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeParametrizable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
          eType="#//core/TypeParameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parametrizable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//core/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Initializable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" eType="#//core/InitialValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InitialValue" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayTypable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arrayDimensions" upperBound="-1"
          eType="#//core/ArrayDimension" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Instantiation" abstract="true" eSuperTypes="#//types/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" unique="false"
          upperBound="-1" eType="#//core/Classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NewConstructorCall" eSuperTypes="#//core/Instantiation #//core/PrimaryReference #//core/MemberContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classTypeArguments" upperBound="-1"
          eType="#//core/Classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExplicitConstructorCall" eSuperTypes="#//core/Instantiation #//core/PrimaryReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="callTarget" eType="#//core/SelfReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayInstantiationBySize" eSuperTypes="#//expressions/Expression #//types/TypedElement #//core/ArrayTypable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sizes" upperBound="-1"
          eType="#//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayInstantiationByValues" eSuperTypes="#//expressions/Expression #//types/TypedElement #//core/ArrayTypable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arrayInitializer" eType="#//core/ArrayInitializer"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayInitializer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arrayInitializers" upperBound="-1"
          eType="#//core/ArrayInitializer" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialValues" upperBound="-1"
          eType="#//core/InitialValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="#//types/Type #//core/TypeParametrizable #//core/Member #//core/NamedElement #//statements/Statement #//core/ReferenceableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" upperBound="-1"
          eType="#//modifiers/Modifier" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MemberContainer" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
          eType="#//core/Member" containment="true" eKeys="#//core/NamedElement/name"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//core/Classifier #//core/MemberContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//core/QualifiedTypeArgument"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
          eType="#//core/QualifiedTypeArgument" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//core/Classifier #//core/MemberContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
          eType="#//core/QualifiedTypeArgument" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//core/Classifier #//core/MemberContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
          eType="#//core/EnumConstant" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
          eType="#//core/Classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumConstant" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
          eType="#//core/Member" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Member" abstract="true" eSuperTypes="#//core/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Constructor" eSuperTypes="#//core/Member #//core/Parametrizable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" upperBound="-1"
          eType="#//modifiers/Modifier" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exceptions" upperBound="-1"
          eType="#//core/Classifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//core/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
          eType="#//core/TypeParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#//annotations/AnnotationInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//core/Member #//core/Initializable #//core/Variable #//core/ReferenceableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="additionalFields" upperBound="-1"
          eType="#//core/AdditionalLocalVariable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#//annotations/AnnotationInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AdditionalField" eSuperTypes="#//core/ReferenceableElement #//core/ArrayTypable #//core/Initializable"/>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//types/TypedElement #//core/ArrayTypable #//core/TypeParametrizable #//core/Parametrizable #//core/Member #//core/ReferenceableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" upperBound="-1"
          eType="#//modifiers/Modifier" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exceptions" upperBound="-1"
          eType="#//core/Classifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//core/Block"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#//annotations/AnnotationInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//core/NamedElement #//types/TypedElement #//core/ArrayTypable #//core/ReferenceableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" upperBound="-1"
          eType="#//modifiers/Modifier" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
          eType="#//core/Classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true" eSuperTypes="#//core/Variable"/>
    <eClassifiers xsi:type="ecore:EClass" name="OrdinaryParameter" eSuperTypes="#//core/Parameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="VariableLengthParameter" eSuperTypes="#//core/Parameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="LocalVariable" eSuperTypes="#//core/Variable #//core/Initializable #//statements/ForLoopInitializer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="additionalLocalVariables"
          upperBound="-1" eType="#//core/AdditionalLocalVariable" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AdditionalLocalVariable" eSuperTypes="#//core/ReferenceableElement #//core/ArrayTypable #//core/Initializable"/>
    <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//core/Member #//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" upperBound="-1"
          eType="#//modifiers/Modifier" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
          eType="#//statements/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayDimension"/>
    <eClassifiers xsi:type="ecore:EClass" name="Primary">
      <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//core/Reference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="#//literals/Literal"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelfReference" eSuperTypes="#//core/PrimaryReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="This" eSuperTypes="#//core/SelfReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="Super" eSuperTypes="#//core/SelfReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassLiteral" eSuperTypes="#//core/PrimaryReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="PackageDescriptor" eSuperTypes="#//core/Classifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//core/PackageDescriptor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifiers" upperBound="-1"
          eType="#//core/Classifier"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="comments" nsURI="http://www.emftext.org/java/comments" nsPrefix="comments">
    <eClassifiers xsi:type="ecore:EClass" name="Comment" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SingleLineComment" eSuperTypes="#//comments/Comment"/>
    <eClassifiers xsi:type="ecore:EClass" name="MultiLineComment" eSuperTypes="#//comments/Comment"/>
    <eClassifiers xsi:type="ecore:EClass" name="Commentable" abstract="true">
      <eAnnotations source="isPutEverywhere"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
          eType="#//comments/Comment" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="http://www.emftext.org/java/expressions"
      nsPrefix="expressions">
    <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//core/InitialValue #//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalExpression"
          eType="#//expressions/ConditionalExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assignmentOperator" eType="#//expressions/AssignmentOperator"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParExpression" eSuperTypes="#//core/PrimaryReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionList" eSuperTypes="#//statements/ForLoopInitializer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
          eType="#//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionalAndExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inclusiveOrExpression"
          upperBound="-1" eType="#//expressions/InclusiveOrExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionalOrExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalAndExpression"
          upperBound="-1" eType="#//expressions/ConditionalAndExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalOrExpression"
          eType="#//expressions/ConditionalOrExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
          eType="#//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InclusiveOrExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exclusiveOrExpression"
          upperBound="-1" eType="#//expressions/ExclusiveOrExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExclusiveOrExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="andExpression" upperBound="-1"
          eType="#//expressions/AndExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AndExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="equalityExpression" upperBound="-1"
          eType="#//expressions/EqualityExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EqualityExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instanceOfExpression"
          upperBound="-1" eType="#//expressions/InstanceOfExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="equal" upperBound="-1"
          eType="#//expressions/Equal" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="notEqual" upperBound="-1"
          eType="#//expressions/NotEqual" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceOfExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationExpression" eType="#//expressions/RelationExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//types/TypeReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RelationExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="shiftExpression" upperBound="-1"
          eType="#//expressions/ShiftExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationOperator" upperBound="-1"
          eType="#//expressions/RelationOperator" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ShiftExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="additiveExpression" upperBound="-1"
          eType="#//expressions/AdditiveExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="shiftOperator" upperBound="-1"
          eType="#//expressions/ShiftOperator" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AdditiveExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicativeExpression"
          upperBound="-1" eType="#//expressions/MultiplicativeExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="additiveOperator" upperBound="-1"
          eType="#//expressions/AdditiveOperator" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultiplicativeExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="unaryExpression" upperBound="-1"
          eType="#//expressions/UnaryExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicativeOperator"
          upperBound="-1" eType="#//expressions/MultiplicativeOperator" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="additiveOperator" eType="#//expressions/AdditiveOperator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="plusplus" eType="#//expressions/PlusPlus"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minusminus" eType="#//expressions/MinusMinus"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unaryExpressionNotPlusMinus"
          eType="#//expressions/UnaryExpressionNotPlusMinus" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnaryExpressionNotPlusMinus" eSuperTypes="#//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="primary" eType="#//core/Primary"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="castExpression" eType="#//expressions/CastExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="complement" eType="#//expressions/Complement"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="negate" eType="#//expressions/Negate"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="plusplus" eType="#//expressions/PlusPlus"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minusminus" eType="#//expressions/MinusMinus"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CastExpression" eSuperTypes="#//core/ArrayTypable #//comments/Commentable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveType" eType="#//types/PrimitiveType"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//types/TypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unaryExpression" eType="#//expressions/UnaryExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unaryExpressionNotPlusMinus"
          eType="#//expressions/UnaryExpressionNotPlusMinus" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RelationOperator" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="LessThan" eSuperTypes="#//expressions/RelationOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="LessThanOrEqual" eSuperTypes="#//expressions/RelationOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="GreaterThan" eSuperTypes="#//expressions/RelationOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="GreaterThanOrEqual" eSuperTypes="#//expressions/RelationOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="ShiftOperator" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="LeftShift" eSuperTypes="#//expressions/ShiftOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="RightShift" eSuperTypes="#//expressions/ShiftOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnsignedRightShift" eSuperTypes="#//expressions/ShiftOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="Equal"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssignmentOperator" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentMinus" eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentPlus" eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentMultiplication"
        eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentDivision" eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentModulo" eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentAnd" eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentOr" eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentExclusiveOr" eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentLeftShift" eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentRightShift" eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundAssignmentUnsignedRightShift"
        eSuperTypes="#//expressions/AssignmentOperator"/>
    <eClassifiers xsi:type="ecore:EClass" name="NotEqual"/>
    <eClassifiers xsi:type="ecore:EClass" name="AdditiveOperator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultiplicativeOperator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PlusPlus"/>
    <eClassifiers xsi:type="ecore:EClass" name="MinusMinus"/>
    <eClassifiers xsi:type="ecore:EClass" name="Complement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Negate"/>
  </eSubpackages>
  <eSubpackages name="literals" nsURI="http://www.emftext.org/java/literals" nsPrefix="literals">
    <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" eSuperTypes="#//literals/Literal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FloatingPointLiteral" eSuperTypes="#//literals/Literal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CharacterLiteral" eSuperTypes="#//literals/Literal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//literals/Literal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="#//literals/Literal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NullLiteral" eSuperTypes="#//literals/Literal"/>
    <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//annotations/AnnotationElementValue"/>
  </eSubpackages>
  <eSubpackages name="modifiers" nsURI="http://www.emftext.org/java/modifiers" nsPrefix="modifiers">
    <eClassifiers xsi:type="ecore:EClass" name="Modifier" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Public" eSuperTypes="#//modifiers/Modifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Abstract" eSuperTypes="#//modifiers/Modifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Protected" eSuperTypes="#//modifiers/Modifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Private" eSuperTypes="#//modifiers/Modifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Final" eSuperTypes="#//modifiers/Modifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Static" eSuperTypes="#//modifiers/Modifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Native" eSuperTypes="#//modifiers/Modifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Synchronized" eSuperTypes="#//modifiers/Modifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Transient" eSuperTypes="#//modifiers/Modifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Volatile" eSuperTypes="#//modifiers/Modifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Strictfp" eSuperTypes="#//modifiers/Modifier"/>
  </eSubpackages>
  <eSubpackages name="statements" nsURI="http://www.emftext.org/java/statements" nsPrefix="statements">
    <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="#//comments/Commentable"/>
    <eClassifiers xsi:type="ecore:EClass" name="Assert" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression1" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression2" eType="#//expressions/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ifStatement" lowerBound="1"
          eType="#//statements/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatement" eType="#//statements/Statement"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
          eType="#//statements/NormalSwitchCase" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//statements/DefaultSwitchCase"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//expressions/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchCase" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1"
          eType="#//statements/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="break" eType="#//statements/Break"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NormalSwitchCase" eSuperTypes="#//statements/SwitchCase"/>
    <eClassifiers xsi:type="ecore:EClass" name="DefaultSwitchCase" eSuperTypes="#//statements/SwitchCase"/>
    <eClassifiers xsi:type="ecore:EClass" name="ForLoop" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//statements/ForLoopInitializer"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="updates" upperBound="-1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//statements/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForLoopInitializer" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ForEachLoop" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//core/OrdinaryParameter"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="collection" eType="#//expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//statements/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhileLoop" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//statements/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DoWhileLoop" eSuperTypes="#//statements/WhileLoop"/>
    <eClassifiers xsi:type="ecore:EClass" name="TryBlock" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tryBlock" lowerBound="1"
          eType="#//core/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="finallyBlock" eType="#//core/Block"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="catches" upperBound="-1"
          eType="#//statements/CatchClause" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CatchClause">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//core/OrdinaryParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="catchBlock" lowerBound="1"
          eType="#//core/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SynchronizedBlock" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lockExpression" eType="#//expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//core/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Throw" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Break" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Continue" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmptyStatement" eSuperTypes="#//statements/Statement"/>
    <eClassifiers xsi:type="ecore:EClass" name="JumpLabel" eSuperTypes="#//statements/Statement #//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statement" lowerBound="1"
          eType="#//statements/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalVariableStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//core/LocalVariable"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="types" nsURI="http://www.emftext.org/java/types" nsPrefix="types">
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeReference" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//types/TypeReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeReferenceSequence" eSuperTypes="#//types/TypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
          eType="#//core/ParameterizedPackageOrClassifierReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true" eSuperTypes="#//core/PrimaryReference #//types/TypeReference #//types/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//types/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Char" eSuperTypes="#//types/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Byte" eSuperTypes="#//types/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Short" eSuperTypes="#//types/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Int" eSuperTypes="#//types/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Long" eSuperTypes="#//types/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//types/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Double" eSuperTypes="#//types/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="VoidLiteral" eSuperTypes="#//types/PrimitiveType"/>
  </eSubpackages>
</ecore:EPackage>
