<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="owl"
    nsURI="http://org.emftext/owl.ecore" nsPrefix="owl">
  <eClassifiers xsi:type="ecore:EClass" name="IRIIdentified" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URIIdentified" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotateable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//Annotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ontology" eSuperTypes="#//URIIdentified #//Annotateable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionIRI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Ontology"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="frames" upperBound="-1"
        eType="#//Frame" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OntologyDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ontology" lowerBound="1"
        eType="#//Ontology" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" upperBound="-1"
        eType="#//Namespace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//Annotateable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotationProperty" lowerBound="1"
        upperBound="-1" eType="#//AnnotationProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        upperBound="-1" eType="#//Target" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IRITarget" eSuperTypes="#//Target">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//IRIIdentified"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralTarget" eSuperTypes="#//Target">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" lowerBound="1"
        eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="#//URIIdentified">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Frame" abstract="true" eSuperTypes="#//IRIIdentified"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="#//Frame"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataProperty" eSuperTypes="#//Feature #//Annotateable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" upperBound="-1"
        eType="#//Description" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" upperBound="-1"
        eType="#//DataRange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characteristic" eType="#//Characteristic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superProperties" upperBound="-1"
        eType="#//DataProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equivalentProperties" upperBound="-1"
        eType="#//DataProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disjointProperties" upperBound="-1"
        eType="#//DataProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationProperty" eSuperTypes="#//Frame #//Annotateable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domains" upperBound="-1"
        eType="#//IRIIdentified"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ranges" upperBound="-1"
        eType="#//IRIIdentified"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superAnnotationProperties"
        upperBound="-1" eType="#//AnnotationProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Frame #//Annotateable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClassesDescriptions"
        upperBound="-1" eType="#//Description" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equivalentClassesDescriptions"
        upperBound="-1" eType="#//Description" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disjointWithClassesDescriptions"
        upperBound="-1" eType="#//Description" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disjointUnionWithClassesDescriptions"
        upperBound="-1" eType="#//Description" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectProperty" eSuperTypes="#//Feature #//Annotateable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyDomain" upperBound="-1"
        eType="#//Description" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyRange" upperBound="-1"
        eType="#//Description" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characteristics" upperBound="-1"
        eType="#//Characteristic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superProperties" upperBound="-1"
        eType="#//ObjectPropertyReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equivalentProperties" upperBound="-1"
        eType="#//ObjectPropertyReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disjointProperties" upperBound="-1"
        eType="#//ObjectPropertyReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inverseProperties" upperBound="-1"
        eType="#//ObjectPropertyReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPropertyChains" upperBound="-1"
        eType="#//ObjectPropertyReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Individual" eSuperTypes="#//Frame #//Annotateable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Description" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="facts" upperBound="-1"
        eType="#//Fact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sameAs" upperBound="-1"
        eType="#//Individual"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="differentFrom" upperBound="-1"
        eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype" eSuperTypes="#//Frame #//Annotateable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRange" eType="#//DataRange"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Misc" abstract="true" eSuperTypes="#//Frame #//Annotateable"/>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalentClasses" eSuperTypes="#//Misc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" lowerBound="1"
        upperBound="-1" eType="#//Description" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisjointClasses" eSuperTypes="#//Misc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" lowerBound="1"
        upperBound="-1" eType="#//Description" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalentProperties" eSuperTypes="#//Misc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectProperties" lowerBound="1"
        upperBound="-1" eType="#//ObjectProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisjointProperties" eSuperTypes="#//Misc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectProperties" lowerBound="1"
        upperBound="-1" eType="#//ObjectProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SameIndividuals" eSuperTypes="#//Misc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" lowerBound="1"
        upperBound="-1" eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifferentIndividuals" eSuperTypes="#//Misc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" lowerBound="1"
        upperBound="-1" eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasKey" eSuperTypes="#//Misc">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverse" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="#//Description" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataRange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataConjunctions" lowerBound="1"
        upperBound="-1" eType="#//DataConjunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataConjunction" eSuperTypes="#//DataRange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPrimaries" lowerBound="1"
        upperBound="-1" eType="#//DataPrimary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPrimary" abstract="true" eSuperTypes="#//DataRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="not" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatatypeReference" eSuperTypes="#//DataPrimary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="theDatatype" lowerBound="1"
        eType="#//Datatype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
        eType="#//Facet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Facet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="facetType" lowerBound="1"
        eType="#//FacetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" lowerBound="1"
        eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FacetType">
    <eLiterals name="LENGTH" value="1" literal="length"/>
    <eLiterals name="MIN_LENGTH" value="2" literal="minLength"/>
    <eLiterals name="MAX_LENGTH" value="3" literal="maxLength"/>
    <eLiterals name="PATTERN" value="4" literal="pattern"/>
    <eLiterals name="LANG_PATTERN" value="5" literal="langPattern"/>
    <eLiterals name="LESS_EQUALS" value="6" literal="&lt;="/>
    <eLiterals name="LESS" value="7" literal="&lt;"/>
    <eLiterals name="GREATER" value="8" literal=">"/>
    <eLiterals name="GREATER_EQUALS" value="9" literal=">="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedDataRange" eSuperTypes="#//DataPrimary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRange" lowerBound="1"
        eType="#//DataRange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPrimaryLiterals" eSuperTypes="#//DataPrimary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" lowerBound="1"
        upperBound="-1" eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fact" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="not" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyFact" eSuperTypes="#//Fact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectProperty" lowerBound="1"
        eType="#//ObjectProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual" lowerBound="1"
        eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyFact" eSuperTypes="#//Fact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataProperty" lowerBound="1"
        eType="#//DataProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" lowerBound="1"
        eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Characteristic">
    <eLiterals name="FUNCTIONAL" value="1" literal="Functional"/>
    <eLiterals name="INVERSE_FUNCTIONAL" value="2" literal="InverseFunctional"/>
    <eLiterals name="REFLEXIVE" value="3" literal="Reflexive"/>
    <eLiterals name="IRREFLEXIVE" value="4" literal="Irreflexive"/>
    <eLiterals name="SYMETRIC" value="5" literal="Symmetric"/>
    <eLiterals name="ASYMETRIC" value="6" literal="Asymmetric"/>
    <eLiterals name="TRANSITIVE" value="7" literal="Transitive"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description" abstract="true" eSuperTypes="#//Annotateable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Disjunction" eSuperTypes="#//Description">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conjunctions" lowerBound="1"
        upperBound="-1" eType="#//Description" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conjunction" eSuperTypes="#//Description">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clazz" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaries" upperBound="-1"
        eType="#//Description" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Primary" abstract="true" eSuperTypes="#//Description">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="not" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualsAtomic" eSuperTypes="#//Primary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" upperBound="-1"
        eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAtomic" eSuperTypes="#//Primary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clazz" lowerBound="1" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedDescription" eSuperTypes="#//Primary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="#//Description" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureRestriction" abstract="true"
      eSuperTypes="#//Primary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverse" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyRestriction" abstract="true"
      eSuperTypes="#//Primary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverse" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectProperty" lowerBound="1"
        eType="#//ObjectProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectProperty" lowerBound="1"
        eType="#//ObjectProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverse" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertySome" eSuperTypes="#//FeatureRestriction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primary" eType="#//Primary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPrimary" eType="#//DataPrimary"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyOnly" eSuperTypes="#//FeatureRestriction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primary" eType="#//Primary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPrimary" eType="#//DataPrimary"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyValue" eSuperTypes="#//FeatureRestriction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual" eType="#//Individual"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="#//Literal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertySelf" eSuperTypes="#//ObjectPropertyRestriction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyMin" eSuperTypes="#//FeatureRestriction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primary" eType="#//Primary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPrimary" eType="#//DataPrimary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyMax" eSuperTypes="#//FeatureRestriction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primary" eType="#//Primary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPrimary" eType="#//DataPrimary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyExactly" eSuperTypes="#//FeatureRestriction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primary" eType="#//Primary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPrimary" eType="#//DataPrimary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theDatatype" lowerBound="1"
        eType="#//Datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbbreviatedXSDStringLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbbreviatedRDFTextLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageTag" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecimalLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preComma" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postComma" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingPointLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
</ecore:EPackage>
