<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hamburger_simple"
    nsURI="http://www.emftext.org/language/hamburger_simple" nsPrefix="hamburger_simple">
  <eClassifiers xsi:type="ecore:EClass" name="Hamburger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toppings" upperBound="-1"
        eType="#//Topping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topping" abstract="true" eSuperTypes="#//RefHamburgerToppings"/>
  <eClassifiers xsi:type="ecore:EClass" name="Meat" eSuperTypes="#//Topping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Onions" eSuperTypes="#//Topping"/>
  <eClassifiers xsi:type="ecore:EClass" name="Salad" eSuperTypes="#//Topping"/>
  <eClassifiers xsi:type="ecore:EClass" name="Menu">
    <eStructuralFeatures xsi:type="ecore:EReference" name="burger" lowerBound="1"
        eType="#//Hamburger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fries" eType="#//Fries"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drink" eType="#//SoftDrink"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fries" eSuperTypes="#//RefMenuFries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="#//Size"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//RefMenuFries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftDrink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="#//Size"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Size">
    <eLiterals name="small"/>
    <eLiterals name="medium" value="1"/>
    <eLiterals name="large" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EEnum0"/>
  <eClassifiers xsi:type="ecore:EClass" name="RefHamburgerToppings" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RefMenuFries" abstract="true"/>
</ecore:EPackage>
