<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tbool"
    nsURI="http://www.emftext.org/language/tbool" nsPrefix="tbool">
  <eClassifiers xsi:type="ecore:EClass" name="ClassTemplate" eSuperTypes="../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//Template">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.bool/metamodel/bool.ecore#//Class"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfElseTypedElement" eSuperTypes="../../org.emftext.language.bool/metamodel/bool.ecore#//TypedElementType ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfElse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.bool/metamodel/bool.ecore#//TypedElementType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBody" eType="ecore:EClass ../../org.emftext.language.bool/metamodel/bool.ecore#//TypedElementType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfElseNamedElement" eSuperTypes="../../org.emftext.language.bool/metamodel/bool.ecore#//NamedElementName ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfElse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.bool/metamodel/bool.ecore#//NamedElementName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBody" eType="ecore:EClass ../../org.emftext.language.bool/metamodel/bool.ecore#//NamedElementName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfClass" eSuperTypes="../../org.emftext.language.bool/metamodel/bool.ecore#//ClassMembers ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//If">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.bool/metamodel/bool.ecore#//ClassMembers"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForClass" eSuperTypes="../../org.emftext.language.bool/metamodel/bool.ecore#//ClassMembers ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForEach">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.emftext.language.bool/metamodel/bool.ecore#//ClassMembers"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
