<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml_class"
    nsURI="http://org.emftext/uml_class" nsPrefix="uml_class">
  <eClassifiers xsi:type="ecore:EClass" name="ClassDiagramm" eSuperTypes="#//XClassDiagramm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
        eType="#//XAssociation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" upperBound="-1"
        eType="#//XClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveDatatypes" upperBound="-1"
        eType="#//XDataType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveDataType" eSuperTypes="#//XDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//XMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="#//AccessType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" eType="#//XClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//XParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" upperBound="-1"
        eType="#//ModifierType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="p_return" eType="#//XDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//XAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="#//AccessType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//XClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" upperBound="-1"
        eType="#//ModifierType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="p_type" eType="#//XDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//XParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//XClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="p_type" eType="#//XDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//XClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" upperBound="-1"
        eType="#//XClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//XAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" upperBound="-1"
        eType="#//XMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="#//AccessType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" upperBound="-1"
        eType="#//ModifierType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//XAssociation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XAttribute" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="XAssociation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="XMethod" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="XParameter" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="XClassDiagramm" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessType">
    <eLiterals name="public"/>
    <eLiterals name="private" value="1"/>
    <eLiterals name="protected" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModifierType">
    <eLiterals name="abstract"/>
    <eLiterals name="final" value="1"/>
    <eLiterals name="static" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//PrimitiveDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../org.emftext.language.primitive_types/metamodel/primitive_types.ecore#//StringObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//PrimitiveDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../org.emftext.language.primitive_types/metamodel/primitive_types.ecore#//BooleanObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//PrimitiveDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../org.emftext.language.primitive_types/metamodel/primitive_types.ecore#//IntegerObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XDataType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="XClass" abstract="true"/>
</ecore:EPackage>
