<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="custom_sandwich"
    nsURI="http://www.emftext.org/language/custom_sandwich" nsPrefix="custom_sandwich">
  <eClassifiers xsi:type="ecore:EClass" name="MenuTemplate" eSuperTypes="../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//Template">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//Menu"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForRefHamburgerToppings" eSuperTypes="../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//RefHamburgerToppings ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//RefHamburgerToppings"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfRefMenuFries" eSuperTypes="../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//RefMenuFries ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//RefMenuFries"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhAttMeatWeight" eSuperTypes="../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//AttMeatWeight ../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//Placeholder"/>
</ecore:EPackage>
