<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="custom_sandwich"
    nsURI="http://www.emftext.org/language/custom_sandwich" nsPrefix="custom_sandwich">
  <eClassifiers xsi:type="ecore:EClass" name="RecipeTemplate" eSuperTypes="../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//Template">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//Recipe"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForRefRecipeIngredients" eSuperTypes="../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//ForLoop ../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//RefRecipeIngredients">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//RefRecipeIngredients"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfRefRecipeIngredients" eSuperTypes="../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//IfCondition ../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//RefRecipeIngredients">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="ecore:EClass ../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//RefRecipeIngredients"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhAttIngredientName" eSuperTypes="../../org.emftext.language.template_concepts/metamodel/template_concepts.ecore#//Placeholder ../../org.emftext.language.sandwich/metamodel/sandwich.ecore#//AttIngredientName"/>
</ecore:EPackage>
