<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:rolecore="http://www.emftext.org/language/rolecore" name="riehle97">
  <eClassifiers xsi:type="ecore:EClass" name="Customer" abstract="true" interface="true">
    <eOperations name="getAccounts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//CustomerRole" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomerRole" abstract="true" eSuperTypes="#//Customer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="core" lowerBound="1" eType="#//CustomerCore"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomerCore" eSuperTypes="#//Customer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Credit" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//CreditRole" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreditRole" abstract="true" eSuperTypes="#//Credit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="core" lowerBound="1" eType="#//CreditCore"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreditCore" eSuperTypes="#//Credit"/>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityObject" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//SecurityObjectRole" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityObjectRole" abstract="true"
      eSuperTypes="#//SecurityObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="core" lowerBound="1" eType="#//SecurityObjectCore"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityObjectCore" eSuperTypes="#//SecurityObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Borrower" eSuperTypes="#//CustomerRole">
    <eOperations name="getCredits" eType="rolecore:CoreClass riehle97.rolecore#//@coreClasses.1"/>
    <eOperations name="getSecurityObject" eType="rolecore:CoreClass riehle97.rolecore#//@coreClasses.2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Investor" eSuperTypes="#//CustomerRole"/>
</ecore:EPackage>
