<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="javaforms"
    nsURI="http://www.emftext.org/language/javaforms" nsPrefix="javaforms">
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalItem" eSuperTypes="../../org.emftext.language.forms/metamodel/forms.ecore#//Item ../../org.emftext.language.java/metamodel/java.ecore#//variables/LocalVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#_Wo2YDNz1Ed2bJ_pQViWxFg"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
