<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reusejava"
    nsURI="http://www.emftext.org/reusejava" nsPrefix="reusejava">
  <eClassifiers xsi:type="ecore:EClass" name="MemberSlot" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//members/Member ../../org.emftext.language.java/metamodel/java.ecore#//references/ReferenceableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatementPrototype" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//members/Member">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" lowerBound="1"
        eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//statements/Statement"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
