/*******************************************************************************
 * Copyright (C) 2012
 * The Stanford Natural Language Processing Group 
 * http://nlp.stanford.edu/
 * This Eclipse plugin matches the Stanford CoreNLP version 1.3.3
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 ******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. TsurgeonParserTreeConstants.java Version 5.0 */
package edu.stanford.nlp.trees.tregex.tsurgeon;

public interface TsurgeonParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTOPERATION = 1;
  public int JJTLOCATION = 2;
  public int JJTNODESELECTIONLIST = 3;
  public int JJTNODESELECTION = 4;
  public int JJTNODENAME = 5;
  public int JJTTREEROOT = 6;
  public int JJTTREENODE = 7;
  public int JJTTREEDTRS = 8;


  public String[] jjtNodeName = {
    "Root",
    "Operation",
    "Location",
    "NodeSelectionList",
    "NodeSelection",
    "NodeName",
    "TreeRoot",
    "TreeNode",
    "TreeDtrs",
  };
}
/* JavaCC - OriginalChecksum=f768a367fd45fc9272bb40a8f1af56ce (do not edit this line) */
